### ISSUE TITLE
Trace-X Release 23.12 Security Acceptance Criteria

### ISSUE THREAD

**Issue by kelaja** [eclipse-tractusx/sig-release#131]
# Release Security 23.12

Source in Catena-X Confluence and Expert Contacts [here](https://confluence.catena-x.net/x/DOZkBQ)(Source only accessible for Catena-X Consortia members in current transition phase).

- [x] **Threat Modelling Analysis results**
  Analysis completed (operations excluded):
  
    - List of risks generated or updated, rated & actions defined
    - Risks accepted or mitigation actions implemented and tested
    - no high threats acceptable

  _Artifact Repository:_
  
    - risk register (decentral on Catena-X confluence)

  _Prime Contacts:_
  
    - Security Team: SEC0

- [x] **Static Application Security Testing (SAST)**
  - code must be scanned weekly with Veracode tool
  - medium risks require mitigation statement
  - high and above not accepted

  _Best Practise:_
  
    - Confirm relevant repository as early as possible to SEC team to enable regular, automated scans. Evidence required for Gate approval.

  _Artifact Repository:_
  
    - Veracode UI
    - (+ GitHub Action)

  _Prime Contacts:_
  
    - Security Team: SEC1

- [x] **Dynamic Application Security Testing (DAST)**
  incl API testing (if applicable)
  - all findings assessed
  - high & very high findings mitigated
  - evidence by re-scan

  _Best Practise:_
  
    - Confirm relevant repository as early as possible to SEC team to enable regular, automated scans. Evidence required for Gate approval.

  _Artifact Repository:_
  
    - INVICTI tool

  _Prime Contacts:_
  
    - Security Team: SEC3 SEC4

- [x] **Secret scanning**
  Scan executed centrally by SEC team and ZERO valid findings
  
  _Artifact Repository:_
  
    - Veracode or alternative tool
    - GitHub Secret Scanning
    - GitGuardian

  _Best Practise:_
  
    - Confirm relevant repository as early as possible to SEC team to enable regular, automated scans. Evidence required for Gate approval.

   _Prime Contact:_
  
     - Security Team: SEC1

- [x] **Software Composition Analysis (SCA)**
  Dependencies must be scanned with Veracode tool with regards to vulnerability
    - high and above not accepted
    - FOSS whitelist policy has to be passed

  _Best Practise:_
  
    - Confirm relevant repository as early as possible to SEC team to enable regular, automated scans. Evidence required for Gate approval.

  _Artifact Repository:_
  
    - Veracode UI
    - (& GitHub Action)

  _Prime Contacts:_
  
    - Security Team: SEC1

- [x] **Container Scan conducted**
  All containers in GitHub Packages must be scanned
  
    - High / Critical findings not accepted

  _Best Practise:_
  
    - Confirm relevant repository as early as possible to SEC team to enable regular, automated scans. Evidence required for Gate approval.

  _Artifact Repository:_
  
    - Trivy
    - via nightly GitHub Action

  _Prime Contacts:_
  
    - Security Team: SEC2

- [x] **Infrastructure as Code**
  IaC code must be scanned. 
    - Error findings not accepted

   _Best Practise:_
  
    - Confirm relevant repository as early as possible to SEC team to enable regular, automated scans. Evidence required for Gate approval.

  _Artifact Repository:_
  
    - KICS or alternative tool
    - via nightly GitHub Action

  _Prime Contacts:_
  
    - Security Team: SEC2

**Comment by ds-mwesener** [comment]
Static Application Security Testing (SAST):
- Artifacts:
1) [GitHub Frontend Scan Daily](https://github.com/eclipse-tractusx/traceability-foss/actions/runs/6765343014)
2)[GitHub Backend Scan Daily](https://github.com/eclipse-tractusx/traceability-foss/actions/runs/6765051398/job/18384175443)

**Comment by ds-mwesener** [comment]
Hi @kelaja would it be possible to already check the prepared results in my comments above? As the Threat Modelling Analysis will take some time until it is done, it would be great to already have some progress. 

Thanks you very much.

**Comment by mkanal** [comment]
@kelaja @guenterban 
PEN KeyCloak seems not to be working to successfully execute DAST tests. 
https://github.com/eclipse-tractusx/sig-infra/issues/346

**Comment by mkanal** [comment]
@guenterban 
Alignment took place by telephone on 13.11.2023. As there have been no changes since release 3.2, it is not necessary to update the Threat Modelling Analysis results

**Comment by PiotrStys** [comment]
Hi @ds-mwesener,

Regarding DAST, no high/critical findings reported by Invicti.

Speaking about the medium-level findings, please make sure you keep the SSL/TLS certificate updated as it has been reported to expire soon.

**DAST Passed** 

Regards,
Piotr

**Comment by DnlZF** [comment]
Hi,
there are no open GitGuardian findings:


![Image](https://github.com/eclipse-tractusx/sig-release/assets/99189503/9f324f93-2e28-4fa5-89ee-eb573513e859)

-> **Secret scanning approved**

Best regards
Daniel

**Comment by klaudiaZF** [comment]
Hi All,

**SCA Passed** for Backend and Frontend, just please keep in mind SAST did not pass, due to 2 high findings.

<img width="842" alt="Traceability-Foss-Backend" src="https://github.com/eclipse-tractusx/sig-release/assets/148344761/e6d7257d-011a-4de7-b1fd-28273d763a98">


<img width="834" alt="Traceability-Foss-Frontend" src="https://github.com/eclipse-tractusx/sig-release/assets/148344761/c848ecf9-c105-488d-8141-d4c6df1bf387">


Please be also aware that we have few open medium findings.
<img width="948" alt="Traceability-Foss-Backend1" src="https://github.com/eclipse-tractusx/sig-release/assets/148344761/9ec2a557-82e3-4636-873b-884c9162c6f8">

<img width="948" alt="Traceability-Foss-Frontend1" src="https://github.com/eclipse-tractusx/sig-release/assets/148344761/16dc86ce-8d29-4ace-8b9f-2c09ecf66267">

**Comment by mkanal** [comment]
Hello @klaudiaZF 
we have mitigated the SCA. Kindlya ask for an recheck?

**Comment by klaudiaZF** [comment]
Hi @mkanal ,

**High findings** in Veracode are mitigated:

<img width="950" alt="traceability_Foss_Backend" src="https://github.com/eclipse-tractusx/sig-release/assets/148344761/e81170cf-dc96-495e-b3cf-871ebe5a424d">

**Comment by klaudiaZF** [comment]
Hi All,

**SAST passed** for backend and frontend, please keep in mind that the red color on backend screenshot is due to SCA 

<img width="826" alt="Traceability-Foss-Frontend" src="https://github.com/eclipse-tractusx/sig-release/assets/148344761/d1450672-dfc9-4bbc-90b6-7217c1b1ea07">

<img width="832" alt="Traceability-Foss-Backend" src="https://github.com/eclipse-tractusx/sig-release/assets/148344761/5dcf0902-1a2e-46d4-be95-594ac350cc97">

Keep in mind that we have few open medium findings:

<img width="944" alt="Traceability-Foss-Backend1" src="https://github.com/eclipse-tractusx/sig-release/assets/148344761/1f0f047f-1844-4f5c-ad73-21df9d43833f">
<img width="947" alt="Traceability-Foss-Frontend1" src="https://github.com/eclipse-tractusx/sig-release/assets/148344761/67c87ae9-f9ae-4fdd-baf3-428d7e8eb120">

**Comment by klaudiaZF** [comment]
Hi All,
We have new high finding for SCA backend.
Can someone mitigated high finding ? **SCA** for backend **can't be passed** now

<img width="835" alt="traceability_Foss_Backend" src="https://github.com/eclipse-tractusx/sig-release/assets/148344761/e0311e95-1fc7-4169-947b-8670f0ffbac6">

**Comment by ds-mwesener** [comment]
HI @klaudiaZF the scans will be executed against the latest main of our code repository. As the release has been already completed is it okay for you to accept it here and create an issue on our repository to fix the high finding on our latest code base? Otherwise in my opinion it would be good to have a clear timeline how long we need to follow up on high findings regarding older releases. As this can always occur on all projects.

Thanks in advance! 

Kind regards

Max

**Comment by scherersebastian** [comment]
backend has container scanning findings https://github.com/eclipse-tractusx/traceability-foss/security/code-scanning
kics passed

**Comment by ds-mwesener** [comment]
HI @scherersebastian this is a known issue. Please find explanation here: https://github.com/eclipse-tractusx/traceability-foss/issues/354 and here: https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-02/#description

**Comment by klaudiaZF** [comment]
@guenterban is this ok if we pass SCA based on previous scan that didn't had a high vulnerability and fix that new high finding by creating an issue on repository?

**Comment by guenterban** [comment]
**SCA passed**
We had done our snapshot with green light. 
The team has to fix it as a mainenance task.

**Comment by mkanal** [comment]
Hello @guenterban thank you very much.
