### ISSUE TITLE
Logging: Agreement Log

### ISSUE THREAD

**Issue by stephanbcbauer** [eclipse-tractusx/sig-release#253]
## Description

With the EDC legally binding contracts are initiated by the negotiation process.

## Additional information 

- [ ] I'm willing to contribute to this feature

**Comment by stefan-ettl** [comment]
Won't do in PI11

**Comment by lgblaumeiser** [comment]
Hi @stephanbcbauer , I see two options here for the issue, either I close it, because I do not see it fit for further processing or you spend some effort in describing a bit the intention of the issue, so that we have a chance to understand the requirement. Would be nice, if you could indicate, which way to go! Thanks!

**Comment by stephanbcbauer** [comment]
@lgblaumeiser this was an old issue. I was just the creator, ;) The information was provided by somebody else. Let's close this issue.
