### ISSUE TITLE
Easy & Formal Definition of Use Cases

### ISSUE THREAD

**Issue by TomBuchertTSystems** [eclipse-tractusx/sig-release#282]
**Benefit Hypothesis**
Formal Use Case Specific Artifacts like Credentials, Roles, Data Models/Ontologies, Requirements, Policies are required in many places. Having a simple "source" definition, such as Excel, provides a single-source-of-truth: 
- Further formal derivates can be added later by providing an extractor logic
- Maintaining and extending use cases becomes easier
- Participants can "instantiate" their roles over multiple use cases to get their personal view on the dataspace

**Beneficiaries**

- any use case modeller and artifact maintainer
- standard authors
- participants to multiple use cases

**Acceptance Criteria**

- Use Case excel template format including role definition, contract/asset references and taxonomy choice
- Use Case ttl format concept and meta-model
- excel template updater (when ontology changed)
- generator for excel->ttl (when excel changed)
- generator for excel->policies/contractdefinitions

Estimated Story Points:
13 SP

**Comment by drcgjung** [comment]
# Story "Implement Creation and Update of Use Case Excel"

Repository https://github.com/catenax-ng/product-knowledge

## Statement 

As use case developer, I need scripts to create and/or update use case excel templates in order to start or maintain my modelling tasks with an easy user interface.

## Acceptance Criteria

- Finalization of the excel template
- Python scripts based on the online ontology
- usage documentation

## Estimation 

5 SP

**Comment by drcgjung** [comment]
# Story "Create a Use Case Excel To TTL Converter"

Repository https://github.com/catenax-ng/product-knowledge

## Statement 

As use case developer, I need a script to derive a ttl description of my use case from my excel template in order to integrate my use case into the Catena-X namespace and to gain an appropriate excerpt of the Catena-X ontology and taxonomy.

## Acceptance Criteria

- Python scripts based on excel template and online ontology.
- usage documentation

## Estimation 

4 SP

**Comment by drcgjung** [comment]
# Story "Move catenax-ng Repositories to catenax-ev"

Repository https://github.com/catenax-ng/product-ontology

## Statement 

As a Catena-X stakeholder/semantic modelling working group, I want to be able to control the perma-id fork as well as the product-ontology repositories such that the catenax-ng consortial repository can be deleted

## Acceptance Criteria

- New repositories are created
- Their content has been synced
- All references/build processes are transferred
- Original repos are archived.

## Estimation 

3 SP

**Comment by stephanbcbauer** [comment]
Discussed in open refinement -> ready for planning (status Backlog)

**Comment by drcgjung** [comment]
Additional Criteria/Story: Support Behaviour Twin to write a goal-oriented Telematics/Behaviour Prognosis Skill

https://github.com/eclipse-tractusx/knowledge-agents/issues/73

**Comment by drcgjung** [comment]
Remaining Estimated Story Points: 18

**Comment by stephanbcbauer** [comment]
Hello @TomBuchertTSystems  

Since the feature is a 24.05 feature and the development phase for 24.08 is coming to an end, we need a status on the feature. Can you please update the status?

- [ ] Currently you are assigned (Responsible) → Is this correct? If not, please assign the correct contact person
- [ ] Please check whether the status (backlog, work in progress ...) is set correctly
- [ ] Please comment on the current status of the feature
- [ ] Are all SubTasks (issues from other repositories that deal with the feature) linked? → The easiest way is to mention the feature here in the issue (via the ID) so we can see which teams/repositories are involved.
- [ ] Is there a spillover planned?

If you need any clarification, please get in touch, thank you very much.

Stephan

**Comment by stephanbcbauer** [comment]
@TomBuchertTSystems , @drcgjung  This was a feature for milestone 24.05. Is this an ongoing topic? Is it closed? Moved?

**Comment by MaximilianHauer** [comment]
Closed by NSC because no progress. Please reopen and assign an upcoming release if needed.
