### ISSUE TITLE
AAS Agent Bridge (Prototype)

### ISSUE THREAD

**Issue by TomBuchertTSystems** [eclipse-tractusx/sig-release#307]
Benefit Hypothesis

    The AAS Agent will be an adapter which translates SPARQL queries into AAS 3.0 API calls
    Using the AAS Agent, it will be possible to perform/delegate "batch" operations (filtering, assembling, aggregating) which would otherwise take multiple AAS Rest calls in one go, it is a form of compute-to-api approach
    AAS Agent can be used as a "binding agent" to provide an alternative dataspace path to your digital twins

Beneficiaries

    any participant already using AAS technology and wanting to participate in KA use cases
    any application based on KA
    any use case based on KA

Acceptance Criteria

    prototyp (0.x) quality, security can be rudimentary
    straightforward mapping of AAS submodels to a graph
    restricted SPARQL structure
    demonstrate with non-trivial twin structures from CX use cases.

Estimated Story Points:
50 SP

**Comment by drcgjung** [comment]
# Story "Implement a Special Remoting Agent on top of the AAS API"

Repository: https://github.com/eclipse-tractusx/knowledge-agents-aas-bridge

## Statement 

As a (potential) KA participant, I want a SPARQL endpoint to access my AAS registry/server.

## Acceptance Criteria

- prototype for subset of SPARQL
- based on RDF4J
- "Natural" Binding of AAS properties to predicates and classes.

## Estimation 

20 SP

**Comment by stephanbcbauer** [comment]
Discussed in open refinement -> ready for planning (status Backlog)

**Comment by drcgjung** [comment]
Remaining Estimations: 40 SP

**Comment by stephanbcbauer** [comment]
Hello @TomBuchertTSystems  

Since the feature is a 24.05 feature and the development phase for 24.08 is coming to an end, we need a status on the feature. Can you please update the status?

- [ ] Currently you are assigned (Responsible) → Is this correct? If not, please assign the correct contact person
- [ ] Please check whether the status (backlog, work in progress ...) is set correctly
- [ ] Please comment on the current status of the feature
- [ ] Are all SubTasks (issues from other repositories that deal with the feature) linked? → The easiest way is to mention the feature here in the issue (via the ID) so we can see which teams/repositories are involved.
- [ ] Is there a spillover planned?

If you need any clarification, please get in touch, thank you very much.

Stephan

**Comment by bosserf** [comment]
Hi @TomBuchertTSystems, kannst Du das hier bitte noch kommentieren? Danke!
Rolf

**Comment by stephanbcbauer** [comment]
@TomBuchertTSystems , @drcgjung, @bosserf   This was a feature for milestone 24.05. Is this an ongoing topic? Is it closed? Moved?

**Comment by bosserf** [comment]
@TomBuchertTSystems: Hi Tom, can you please comment on this? Thanks!

**Comment by MaximilianHauer** [comment]
Closed by NSC because no progress. Please reopen and assign an upcoming release if needed.

**Comment by bosserf** [comment]
@TomBuchertTSystems + @obalandi : what is the status? I have not received feedback from you, so I am a little bit lost..
