### ISSUE TITLE
PURIS KIT Release Item Stock

### ISSUE THREAD

**Issue by PhillipNalesny** [eclipse-tractusx/sig-release#437]
## Description

Creation and release of KIT Release for Item Stock Standard. Includes Operation View, Adoption View & Develeopment View. 

Further standards will be included in PI13 without official Release

Included standard in R24.05 (PI12):
[(PURIS) CX - 0122 Item Stock Exchange v.1.0.0](https://confluence.catena-x.net/pages/viewpage.action?pageId=100934529#id-(PURIS)OverviewIPClearing/ComplianceByDesign-(PURIS)CX-0122ItemStockExchangev.1.0.0)

Included standards in PI 13: Planned Production Output, Short-Term Material Demand, Item Stock & Delivery Information. 

[(PURIS) CX - 0121 Planned Production Output Exchange v.1.0.0](https://confluence.catena-x.net/pages/viewpage.action?pageId=100934529#id-(PURIS)OverviewIPClearing/ComplianceByDesign-(PURIS)CX-0121PlannedProductionOutputExchangev.1.0.0)

[(PURIS) CX - 0120 Short-Term Material Demand Exchange v.1.0.0](https://confluence.catena-x.net/pages/viewpage.action?pageId=100934529#id-(PURIS)OverviewIPClearing/ComplianceByDesign-(PURIS)CX-0120Short-TermMaterialDemandExchangev.1.0.0)

[(PURIS) CX - 0000 Delivery Information Exchange v.1.0.0](https://confluence.catena-x.net/pages/viewpage.action?pageId=100934529#id-(PURIS)OverviewIPClearing/ComplianceByDesign-(PURIS)CX-0000DeliveryInformationExchangev.1.0.0)
-->

## Impact
Benefit Hypothesis

If we release the item stock as a KIT, it will be better prepared for potential users and thus easier to use. As a result, we hope to see greater acceptance and adoption of the release standards.

Beneficiaries

customers of PURIS will benefit because it will be easier for them to understand the concept of item stock and to adapt it to their needs
-->

## Additional information 

- [x] I'm willing to contribute to this feature

**Comment by stephanbcbauer** [comment]
Hello @PhillipNalesny 

Since the feature is a 24.05 feature and the development phase for 24.08 is coming to an end, we need a status on the feature. Can you please update the status?

- [ ] Currently you are assigned (Responsible) → Is this correct? If not, please assign the correct contact person
- [ ] Please check whether the status (backlog, work in progress ...) is set correctly
- [ ] Please comment on the current status of the feature
- [ ] Are all SubTasks (issues from other repositories that deal with the feature) linked? → The easiest way is to mention the feature here in the issue (via the ID) so we can see which teams/repositories are involved.
- [ ] Is there a spillover planned?

If you need any clarification, please get in touch, thank you very much.

Stephan
