### ISSUE TITLE
PURIS Mini App R24.05

### ISSUE THREAD

**Issue by PhillipNalesny** [eclipse-tractusx/sig-release#439]
## Description

The PURIS Mini App is an application to make the PURIS standards useable for PURIS users. 
For Release 24.05 the PURIS Mini App will be extended by the 3 functionalities: 

1. Dashboard view: a) Visualization of Production Output of supplyer, demand of customer, delivery information b) request function for update of these information 
2. CX Integration / Setup Wizard: To configure the Puris Mini App
3. Messaging View: to create and receive messages from Partners regarding supply bottlenecks

Benefit Hypothesis
In order to have the Fraunhofer FOSS Application ready for release, it needs to reach Quality Gate 5. Therefore it will have the needed maturity to be useful for PURIS Users.

Beneficiaries

PURIS Team to have it ready for release
PURIS Users to have well working software
## Additional information 

- [ ] I'm willing to contribute to this feature

**Comment by stephanbcbauer** [comment]
Hello @PhillipNalesny 

Since the feature is a 24.05 feature and the development phase for 24.08 is coming to an end, we need a status on the feature. Can you please update the status?

- [ ] Currently you are assigned (Responsible) → Is this correct? If not, please assign the correct contact person
- [ ] Please check whether the status (backlog, work in progress ...) is set correctly
- [ ] Please comment on the current status of the feature
- [ ] Are all SubTasks (issues from other repositories that deal with the feature) linked? → The easiest way is to mention the feature here in the issue (via the ID) so we can see which teams/repositories are involved.
- [ ] Is there a spillover planned?

If you need any clarification, please get in touch, thank you very much.

Stephan
