### ISSUE TITLE
Update Documentation

### ISSUE THREAD

**Issue by jzbmw** [eclipse-tractusx/sig-release#450]
## Description

Update all documentation: 
- Data Chain KIT
- API & Interface documentation 
- Arc42 document
- User Manual
- Admin Manual
- Other documentation which needs to be transferred into GitHub from Confluence regarding PCWM

## Link 
- parent of https://github.com/eclipse-tractusx/traceability-foss/issues/489
- parent of https://github.com/eclipse-tractusx/traceability-foss/issues/507

**Comment by stephanbcbauer** [comment]
was presented in open planning ⇾ contributors and committer are involved

**Comment by stephanbcbauer** [comment]
Hello @jzbmw , @mkanal  

Since the feature is a 24.08 feature and the development phase is coming to an end, we need a status on the feature.

- [ ] Currently you are assigned (Responsible) → Is this correct? If not, please assign the correct contact person
- [ ] Please check whether the status (backlog, work in progress ...) is set correctly
- [ ] Please check whether there is an assignment to a committee or expert group (supported-by) to be found on the [board](https://github.com/orgs/eclipse-tractusx/projects/26/views/28)
- [ ] Please comment on the current status of the feature
- [ ] Are all SubTasks (issues from other repositories that deal with the feature) linked? → The easiest way is to mention the feature here in the issue (via the ID) so we can see which teams/repositories are involved.

If you need any clarification, please get in touch, thank you very much.
Stephan

**Comment by stephanbcbauer** [comment]
Hello @jzbmw , @mkanal 
 
In a few weeks, we want to publish Tractus-X Release 24.08. For this, we need a clear status about the features (which will be included in the release and which will be cancelled or postponed to the next release).
 
Currently, the feature is still in status `Work in progress`. Please update the status by 09.07.24 eob.
 
If the feature is not ready for release 24.08, or it is possibly not planned at all, please set the status to `Not in release`. Please remember that in this case, any dependent components must be informed.
 
Thank you and best regards.

**Comment by stephanbcbauer** [comment]
@mkanal  This was a feature for milestone 24.08. Right now, it's in "Not in release", which is fine. What are the plans for the future?

**Comment by mkanal** [comment]
@stephanbcbauer There are no further plans for this issue. There is no active contribution planed for next release.

**Comment by MaximilianHauer** [comment]
Closed by NSC because no progress. Please reopen and assign an upcoming release if needed.
