### ISSUE TITLE
Community Activation

### ISSUE THREAD

**Issue by mkanal** [eclipse-tractusx/sig-release#452]
## Description

We transfer irs to the PCWM in a controlled manner and build up a motivated and well-informed community here at an early stage, which will take over the further development of the product from the middle of the year.

This includes: 
- [ ] Provisioning of tutorials on how to set up, configure, work with the different use cases 
- [ ] Prompt and valuable exchange with the community in the matrix chat to refine and discuss features and issues well and to react promptly and solution-oriented to errors. 
- [ ]  Fast response time and resolution time to errors posted by the community
- [ ] Active participation in the Community days 
- [ ] Online courses and webinars

## Link
- parent of https://github.com/eclipse-tractusx/item-relationship-service/issues/362
- parent of https://github.com/eclipse-tractusx/item-relationship-service/issues/364
- parent of https://github.com/eclipse-tractusx/item-relationship-service/issues/365
- parent of https://github.com/eclipse-tractusx/item-relationship-service/issues/373
- parent of https://github.com/eclipse-tractusx/item-relationship-service/issues/374

## Impact

PCWM 
Tractus-x Community 

## Additional information 
-

**Comment by mkanal** [comment]
## Description


We transfer irs to the PCWM in a controlled manner and build up a motivated and well-informed community here at an early stage, which will take over the further development of the product from the middle of the year.

This includes: 
- [ ] Provisioning of tutorials on how to set up, configure, work with the different use cases 
- [ ] Prompt and valuable exchange with the community in the matrix chat to refine and discuss features and issues well and to react promptly and solution-oriented to errors. 
- [ ]  Fast response time and resolution time to errors posted by the community
- [ ] Active participation in the Community days 
- [ ] Online courses and webinars


## Impact

PCWM 
Tractus-x Community 


## Additional information 
-

**Comment by stephanbcbauer** [comment]
was presented in open planning -> contributors and committer are involved

**Comment by stephanbcbauer** [comment]
Hello @jzbmw, @mkanal 

Since the feature is a 24.08 feature and the development phase is coming to an end, we need a status on the feature.

- [ ] Currently you are assigned (Responsible) → Is this correct? If not, please assign the correct contact person
- [ ] Please check whether the status (backlog, work in progress ...) is set correctly
- [ ] Please check whether there is an assignment to a committee or expert group (supported-by) to be found on the [board](https://github.com/orgs/eclipse-tractusx/projects/26/views/28)
- [ ] Please comment on the current status of the feature
- [ ] Are all SubTasks (issues from other repositories that deal with the feature) linked? → The easiest way is to mention the feature here in the issue (via the ID) so we can see which teams/repositories are involved.

If you need any clarification, please get in touch, thank you very much.
Stephan

**Comment by stephanbcbauer** [comment]
Hello @jzbmw , @mkanal 
 
In a few weeks, we want to publish Tractus-X Release 24.08. For this, we need a clear status about the features (which will be included in the release and which will be cancelled or postponed to the next release).
 
Currently, the feature is still in status `Work in progress`. Please update the status by 09.07.24 eob.
 
If the feature is not ready for release 24.08, or it is possibly not planned at all, please set the status to `Not in release`. Please remember that in this case, any dependent components must be informed.
 
Thank you and best regards.
