### ISSUE TITLE
Technical Maintenance

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/sig-release#473]
## Description
As part of the normal product maintenance, a couple of improvements/technical support items/needed upgrades are identified which are planned to take place.

### Backend 
- .NET 8 upgrade https://github.com/eclipse-tractusx/portal-backend/issues/456
- Move keycloak seeding script from portal-backend to IAM repository - https://github.com/eclipse-tractusx/portal-backend/issues/555
- cleanup swagger docu of mandatory and nullable parameters per endpoint - ongoing

### Frontend
- deprecated react-scripts to be cleaned up/removed https://github.com/eclipse-tractusx/portal-frontend/issues/537; https://github.com/eclipse-tractusx/portal-frontend/issues/506
- cleanup duplication: merge multiple implementations of API calls https://github.com/eclipse-tractusx/portal-frontend/issues/587
- CSS Definitions: Remove duplicate / unused css definition - https://github.com/eclipse-tractusx/portal-frontend/issues/583
- publish code guidelines & link them inside the pr checklist 
- update used naming convention (currently inconsistent) for
  - typescript
  - variables
  - overlays
  - etc.
- clean-up locales/translation files and add missing translation
- portal fe MUI integration https://github.com/eclipse-tractusx/portal-frontend/issues/582
- fix shared component linter failing
- remove unused code (e.g. overlays) https://github.com/eclipse-tractusx/portal-frontend/issues/578
- improve client role handling across multiple clients (Security issue) - https://github.com/eclipse-tractusx/portal-frontend/issues/502

### IAM

- keycloak version upgrade 23 https://github.com/eclipse-tractusx/portal-iam/issues/62
- publish keycloak project to nuget

## Additional information 

- [x] I'm willing to contribute to this feature

**Comment by stephanbcbauer** [comment]
Hello @jjeroch , @evegufy  

Since the feature is a 24.05 feature and the development phase for 24.08 is coming to an end, we need a status on the feature. Can you please update the status?

- [ ] Currently you are assigned (Responsible) → Is this correct? If not, please assign the correct contact person
- [ ] Please check whether the status (backlog, work in progress ...) is set correctly
- [ ] Please comment on the current status of the feature
- [ ] Are all SubTasks (issues from other repositories that deal with the feature) linked? → The easiest way is to mention the feature here in the issue (via the ID) so we can see which teams/repositories are involved.
- [ ] Is there a spillover planned?

If you need any clarification, please get in touch, thank you very much.

Stephan

**Comment by MaximilianHauer** [comment]
milestone removed ,ticket will be reviewed and rescheduled if necessary

**Comment by MaximilianHauer** [comment]
Closed by NSC because no progress. Please reopen and assign an upcoming release if needed.
