### ISSUE TITLE
serviceaccounts API reachable by technical user

### ISSUE THREAD

**Issue by ciprianherciu** [eclipse-tractusx/sig-release#521]
## Description
In order to adopt the auto setup in MSO we need to use the below named API to get technical credentials:
/api/apps/{appId}/subscription/{subscriptionId}/provider
/api/administration/serviceaccount/owncompany/serviceaccounts/{serviceAccountId}

We will need to be able to access the above mentioned API with a technical user.
The MSO needs to trigger the auto setup with a technical user, in order to be operable

## Additional information 

- [ ] I'm willing to contribute to this feature

**Comment by ciprianherciu** [comment]
The adaptation of the auto setup in MSO is at the moment blocked. Caused of the problem is that the technical user can not reach the api needed . Since it is blocked we can not implement it in the Release 24.03 so we will move the milestone to 24.05

**Comment by jjeroch** [comment]
@ciprianherciu can you please provide me the MSO feature where the switch to the new process is planned - I like to link the tickets since at the end we only provide a small functional change while you are implementing a bigger feature in the scope of the MSO.
In case you dont have a feature yet, I suggest to move this ticket here to the MSO repo and I link my task ticket (already existing) to it.

**Comment by ciprianherciu** [comment]
@jjeroch the Feature where we mention the maintenance of the MSO is this one: https://github.com/eclipse-tractusx/sig-release/issues/415

**Comment by stephanbcbauer** [comment]
Hello @ciprianherciu  

Since the feature is a 24.05 feature and the development phase for 24.08 is coming to an end, we need a status on the feature. Can you please update the status?

- [ ] Currently you are assigned (Responsible) → Is this correct? If not, please assign the correct contact person
- [ ] Please check whether the status (backlog, work in progress ...) is set correctly
- [ ] Please comment on the current status of the feature
- [ ] Are all SubTasks (issues from other repositories that deal with the feature) linked? → The easiest way is to mention the feature here in the issue (via the ID) so we can see which teams/repositories are involved.
- [ ] Is there a spillover planned?

If you need any clarification, please get in touch, thank you very much.

Stephan

**Comment by stephanbcbauer** [comment]
@ciprianherciu , @drcgjung This was a feature for milestone 24.05. Is this an ongoing topic? Is it closed? Moved?

**Comment by MaximilianHauer** [comment]
Closed by NSC because no progress. Please reopen and assign an upcoming release if needed.
