### ISSUE TITLE
[Traceability KIT] Release 24.08

### ISSUE THREAD

**Issue by mhellmeier** [eclipse-tractusx/sig-release#573]
This issue tracks all relevant release checks for your KIT.

> [!IMPORTANT]  
> Follow the [guidance on how to use the templates](https://github.com/eclipse-tractusx/sig-release/blob/main/README.md#release-management-acceptance-criteria).

## Release Info

Please provide information on what you want to be included in the Eclipse Tractus-X release.
If you are not the owner of this issue, please provide the information as comment to the issue.
Have your prepared content reviewed by a professional peer group before submitting it for committer approval.
Best practice: have a professional Peer review your prepared content before you submit for expert approvals.
Please link the open or merged PR that includes the changes.

**Version to be included in Eclipse Tractus-X release:** *version placeholder*
- KIT semantic version of change log.
- Date of KIT publication must be aligned with overall release date.

If changes to your KIT are not yet live on [our website](https://eclipse-tractusx.github.io/developer), link the open PR introducing the changes for this release.

If changes are already live, also point out the PRs which included the changes for this version if possible.

- [PR number](pr-url)

# General

- [ ] **CHANGELOG** available and maintained
- [ ] [**Tractus-X Release Guidelines**](https://eclipse-tractusx.github.io/docs/release) fulfilled

# Adoption View

- [ ] **Vision and Mission** statement present
- [ ] **Business Value** statement present
- [ ] **Semantic Models** linked and described
- [ ] **Logic / Schema** available and described
- [ ] **Business Process** documentation available
- [ ] **Access and Usage Policies** documented
- [ ] **Standards** submitted / published via the Catena-X e.V. process and linked with current version (e.g., semantic models)
- [ ] **Tutorials** available
- [ ] **White Paper** available
- [ ] **Notice** CC BY 4.0 licence statement available

# Development View

- [ ] **API Specification** published on [SwaggerHub](https://app.swaggerhub.com/search?owner=eclipse-tractusx-bot)
- [ ] **Protocols** available (e.g., dataspace protocol)
- [ ] **Sample Data** available
- [ ] **Architecture** integration into the overall Catena-X architecture and / or product architecture (e.g., Arc42) available.
- [ ] **Reference Implementation** available

# Operation View

- [ ] **Setup Guide** available (e.g., installation guides)
- [ ] **Deployment Script** available (e.g., helm charts)

# Helpful Links

- [Catena-X standard library](https://catena-x.net/en/standard-library)

**Comment by Grand-Thibault** [comment]
@mhellmeier is this a maintenance task? Please add a description.

**Comment by mhellmeier** [comment]
No, it is not a maintenance task. It is a release of the new KIT documentation.

**Comment by stephanbcbauer** [comment]
@mhellmeier this was not part of the open planning 24.08. What is the status of this feature?

**Comment by stephanbcbauer** [comment]
Hello @mhellmeier 

Since the feature is a 24.08 feature and the development phase is coming to an end, we need a status on the feature.

- [ ] Currently you are assigned (Responsible) → Is this correct? If not, please assign the correct contact person
- [ ] Please check whether the status (backlog, work in progress ...) is set correctly
- [ ] Please check whether there is an assignment to a committee or expert group (supported-by) to be found on the [board](https://github.com/orgs/eclipse-tractusx/projects/26/views/28)
- [ ] Please comment on the current status of the feature
- [ ] Are all SubTasks (issues from other repositories that deal with the feature) linked? → The easiest way is to mention the feature here in the issue (via the ID) so we can see which teams/repositories are involved.

If you need any clarification, please get in touch, thank you very much.
Stephan

**Comment by mhellmeier** [comment]
An updated KIT for release 24.08 is planned. Since I am not part of the corresponding expert group, I can't make a status update here. @FelixHaeckel is responsible for the expert group and their work. I think he can give an update or direct it to the correct person.

**Comment by stephanbcbauer** [comment]
Hello @FelixHaeckel 
 
In a few weeks, we want to publish Tractus-X Release 24.08. For this, we need a clear status about the features (which will be included in the release and which will be cancelled or postponed to the next release).
 
Currently, the feature is still in status `Work in progress`. Please update the status by 09.07.24 eob.
 
If the feature is not ready for release 24.08, or it is possibly not planned at all, please set the status to `Not in release`. Please remember that in this case, any dependent components must be informed.
 
Thank you and best regards.

**Comment by stephanbcbauer** [comment]
@jSchuetz88 as discussed in the meeting i adapted the description since this is the QGate issue for the KIT

Here is the description which was there before




## Description

The Traceability KIT will be updated for release 24.08.

## Impact

Since 24.05 is a breaking change, the Traceability KIT for release 24.08 will only contain additional information, bug fixes, etc.

## Additional information 

- [x] I'm willing to contribute to this feature
