### ISSUE TITLE
[Trace-X] R24.5 Release Checks

### ISSUE THREAD

**Issue by mkanal** [eclipse-tractusx/sig-release#611]
> [!IMPORTANT]  
> Follow the [guidance on how to use the templates](https://github.com/eclipse-tractusx/sig-release/blob/main/README.md#release-management-acceptance-criteria).

# RELEASE 
- HELM Charts: [1.3.38](https://github.com/eclipse-tractusx/traceability-foss/releases/tag/helm-charts-1.3.38)
- Release [11.0.1](https://github.com/eclipse-tractusx/traceability-foss/releases/tag/11.0.1)

## Release Info

Please provide information on what you want to be included in the Eclipse Tractus-X release.
If you are not owner of this issue, please provide the information as comment to the issue.
Make sure to assign this issue to expert(s) for their approval, as soon as you have finished preparation. Multiple assignees allowed; they will un-assign themselves once review completed.

**Version to be included in Eclipse Tractus-X release**: 11.0.1
**Leading product repository:** https://github.com/eclipse-tractusx/traceability-foss/

# Compliance Verifications

This issue tracks all checks, that need to be performed for a product release in Eclipse Tractus-X. 

- [x] **Interoperability** checks performed
- [x] **Data Sovereignty** checks performed
  _Data Sov Tests in progress: Final alignment on Wednesday. https://jira.catena-x.net/browse/TEST-1918_ 

# General Checks

- [x] [**Tractus-X Release Guidelines**](https://eclipse-tractusx.github.io/docs/release)(TRGs) fulfilled https://github.com/eclipse-tractusx/traceability-foss/issues/955
- [x] UUX Checks Compliant with the Style Guide
   - [x] AppWalkThrough on 8.5.2024 @jjeroch
   - [x] UUX Review of app 
   - [x] Provided user accounts for Trace-X Instances Trace-X and BMW  
 https://github.com/eclipse-tractusx/sig-release/issues/611#issuecomment-2134497279

> [!NOTE]
> Note: most criteria for documentation and security are now covered in TRGs

# Security Checks

- [x] **Thread Modelling Analysis** passed

# Test Results

- [x] **E2E Integration Test** passed
 _https://jira.catena-x.net/browse/TEST-1887 Done_
 _https://jira.catena-x.net/browse/TEST-1892 Done_
 _https://jira.catena-x.net/browse/TEST-1888 Done_
 **Findings:** 
 - CLOSED https://github.com/eclipse-tractusx/traceability-foss/issues/956 (identified as not a bug - so I closed it again)
 - OPEN https://github.com/eclipse-tractusx/traceability-foss/issues/957
 - OPEN https://github.com/eclipse-tractusx/traceability-foss/issues/958
- [x] **User Journey** approved

# Helpful Links

- [Eclipse Tractus-X openAPI specs on SwaggerHub](https://app.swaggerhub.com/search?owner=eclipse-tractusx-bot)

**Comment by mkanal** [comment]
User journey was approved by PO @jzbmw.

**Comment by mkanal** [comment]
Good morning @guenterban, @bs-jokri, @pablosec,

in both products (Trace-X FOSS and IRS) there are no relevant system-related changes compared to R23.12 and R24.3. For this reason, we request the release of the QGC "Threat Modeling Analysis passed" based on version R23.12 & R24.3.
If you come to a different conclusion, we will be happy to provide you with dates for the threat modeling analysis.


Sig-Release: 
Trace-X: https://github.com/eclipse-tractusx/sig-release/issues/611
IRS: https://github.com/eclipse-tractusx/sig-release/issues/670

Thank you very much 
IRS and Trace-X Team

**Comment by mkanal** [comment]
Good morning @almadigabor,

would you please again support the Team IRS regarding TRG checks for the upcoming release R24.5? 

Thank you very much

Martin

**Comment by almadigabor** [comment]
> Good morning @almadigabor,
> 
> would you please again support the Team Trace-X regarding TRG checks for the upcoming release R24.5?
> 
> Thank you very much
> 
> Martin

Hi @mkanal, sure, I'll do the TRG checks for Trace-X this time too. :)

**Comment by almadigabor** [comment]
I've opened the TRG checks issue for Trace-X. https://github.com/eclipse-tractusx/traceability-foss/issues/955

**Comment by cbrugg** [comment]
E2E Tests were successfully performed. INT Tests need to be documented/updated. Data Sov Tests outstanding. Thank You!

**Comment by RolaH1t** [comment]
QG review 14-May:
data sov in progress; no blockers expected
TRG completion soon expected; successful collaboration across products & with SystemTeam
two findings identified within E2E tests; will be fixed with patch version
minor version expected for final release (11.0.1 & 1.3.38)
no follow-up mtg required

**Comment by ds-jhartmann** [comment]
QG checks are done and all issues have been fixed. I approve it ✅

**Comment by jjeroch** [comment]
@mkanal please find below the UI/UX Feedback - a couple of findings are also test related.
Did you had an user which tested the app and is not an developer but rather a customer?

## User Experience

**ITEM 1**
Produkte
Language DE: Filter „Eigene“ vs “Eigen” , naming should match 1:1 (Proposal: “Eigene”)

<img width="788" alt="image" src="https://github.com/eclipse-tractusx/sig-release/assets/94133633/49d9dce3-3746-460f-a815-81fc9f461b7e">

<br>
<br>

**ITEM 2**
Dashboard View
Right after entering application, Current: Shown are top 5 Quality and a “View all button”
Proposal: add note that this table shows top 5 only (or if configurable by user add a hint to this option as well) also let the user know what "all" means - how many more are available?

<img width="656" alt="image" src="https://github.com/eclipse-tractusx/sig-release/assets/94133633/a487bdf5-6f70-4157-921e-b2016a796a85">

<br>
<br>

**ITEM 3**
Parts - “Full Width”
-- blocking --
in case of As Planned last column is cut in visibility and scrolling missing

<img width="143" alt="image" src="https://github.com/eclipse-tractusx/sig-release/assets/94133633/a157aafa-0fab-49a3-8dee-3791d6ef26c7">

<br>
<br>

**ITEM 4**
-- blocking --
Parts - Table Column Settings
Cumbersome and not intuitive to change the order of columns; When “selecting” a column it also gets de-selected and will not appear upon clicking “Save”. Sometimes it is not working at all.

<img width="514" alt="image" src="https://github.com/eclipse-tractusx/sig-release/assets/94133633/a8732796-622c-413b-8c2a-3c4abaeb9dc3">

<br>
<br>

**ITEM 5**
-- blocking --
Parts Table (Full width)
Not seeing all selected columns – the seven last are missing and can only view via deselecting others. Tried Scaling the Screen.
Proposal: add Scroll Bar like in other views

<img width="369" alt="image" src="https://github.com/eclipse-tractusx/sig-release/assets/94133633/18574c2a-2ab0-484b-88bf-24a111ec7af9">

<br>
<br>

**ITEM 6**
-- not blocking --
Create Notification
Save Button hard to find – should be with the data entered? Depending on screensize when scrolling down this is not visible

<img width="647" alt="image" src="https://github.com/eclipse-tractusx/sig-release/assets/94133633/6a632b65-da5a-47e7-b52b-be00ddc63678">

<br>
<br>

**ITEM 7**
-- blocking --
Admin View – BPN-EDC Konfiguration
Search option unclear. Search is on the top but actually searching in the section on the bottom. It would be much better to take out the "Add function" from the screen. Go via an "Add Connector" button and work with overlays or half screens . 

<br>
<br>

**ITEM 8**
-- blocking --
Admin View – BPN-EDC Konfiguration
In the View “New Entries” can edit URL and click on save changes – but there original entry is shown and will be acknowledged
proposal : make fields in “new entries” read only, then user has to click remove and retype in the configuration fields

<br>
<br>

**ITEM 9**
-- blocking --
Admin View – BPN-EDC Konfiguration
Window shows “deleted” , “added” and “changed” prior to “save changes” OPTION
However there is no option to edit / change – is there? If not, please remove.

<img width="518" alt="image" src="https://github.com/eclipse-tractusx/sig-release/assets/94133633/29118034-12cd-41b9-b3db-8a4a99c61621">

<br>
<br>

**ITEM 10**
-- blocking --
Quality notifications – Received
Functionality Issue – signed in as role administrator this is unavailable with tooltip below
Same, e.g. when creating a quality alert. Get to the point of entering all data – but Save button is disabled (with role Admin) à should not be able to get to the entry screen in the first place

<img width="575" alt="image" src="https://github.com/eclipse-tractusx/sig-release/assets/94133633/001c9baa-fb4f-4bc8-a3da-a9417cd65c07">


<br>
<br>

**ITEM 11**
-- not blocking --
Help - Portal Configuration
Links to Portal Configuration outdated, some linking to same “Catena-X HelpDesk” but not topic specific https://portal.int.demo.catena-x.net/documentation

Expected: one overall link or dedicated links getting user to specific information

<br>
<br>

**IETM 12**
-- blocking --
HELP
Help section outdate, not in sync with current prod version
See, e.g. “Inbox” or “Other Parts” section

<img width="523" alt="image" src="https://github.com/eclipse-tractusx/sig-release/assets/94133633/43d8e0c0-1bab-456f-b17f-6ad20958a943">


<br>
<br>

**ITEM 13**
-- blocking --
Publish Asset
Section of policy: only one option available and I have no way to see what the content of the policy is (tested with admin role) – where do I find the details?

After selecting policy “publish” button is disabled. No error message. User does not understand why.
-> If role should not publish, then button should already be disabled.

<img width="582" alt="image" src="https://github.com/eclipse-tractusx/sig-release/assets/94133633/feef4851-e48b-4cc7-a8e1-f9e5fc39546b">

<br>
<br>

**ITEM 14**
-- blocking --
PARTS
Part Search not working correctly, Copy/pasting BPN brings no results
ALSO: tool tip fields do not match column names of parts tables
Proposal to use consistent naming conventions across application.

<img width="585" alt="image" src="https://github.com/eclipse-tractusx/sig-release/assets/94133633/abd8aed0-1dda-4f16-8a06-3a7b92851d83">

<br>
<br>

**ITEM 15**
-- blocking --
Parts overview
those with quality alert are marked yellow – not clear to new user
Proposal: add a legend

<br>

---

## StyleGuide Compliance

**ITEM 1**
-- blocking --
Parts, Filter on Supplier
Symbol and ToolTip “Tombstone” – unclear for user, empty data

<img width="596" alt="image" src="https://github.com/eclipse-tractusx/sig-release/assets/94133633/c95324d4-896b-489f-8512-0b73672a6613">

<br>
<br>

**ITEM 2**
-- blocking --
QUALITY INVESTIGATIONS table
- missing frame on right and left side
- button "view all" is unclear - I can see no-where how many records are even available - please add somewhere the - information of record numbers
- button "view all" is also displayed if the table has "0" records; in this case I suggest to disable the button/option

<br>
<br>

**ITEM 3**
-- blocking --
same as the bullet points above also applies for QUALITY ALERTS

<br>
<br>

**ITEM 4**
-- blocking --
Coloring update needed
<img width="309" alt="image" src="https://github.com/eclipse-tractusx/sig-release/assets/94133633/7280f574-558c-43b4-8136-6ccbcb0e0ba5">


<br>
<br>

## Responsivness

**ITEM1**
-- blocking --
Upon clicking approval for just created quality investition, no indication of processing is given
Hitting Details still shows queued view,
Only a while later info at top right of page that approval processed
Table view however, does not get automatically updated / refreshed

<img width="593" alt="image" src="https://github.com/eclipse-tractusx/sig-release/assets/94133633/e1460adc-9d14-439b-8d85-1f415c3e5d4b">

<br>
<br>

**ITEM 2**
-- not blocking --
Trying to approve quality alert
See pop-up error meassage /10:05, 15.5.
No further information given – assuming this happens as BPN is not a valid one à improve and include this information (ideally already check upon entry in the create-View)

<img width="597" alt="image" src="https://github.com/eclipse-tractusx/sig-release/assets/94133633/53d8b9ec-4af0-4486-8bb1-d085a156d413">

<br>
<br>

**ITEM 3**
-- blocking --
New quality alert
In table view à Edit
In edit view hit back button

<img width="608" alt="image" src="https://github.com/eclipse-tractusx/sig-release/assets/94133633/c3a4667b-7b07-4be2-802d-3802c9247317">



<br>
<br>

## Old comments (leftovers)

o TRACEFOSS-897 I miss a kind of user intro. When the user is accessing the app, he/she is a bit lost. Ideally there is a help or a short intro
o TRACEFOSS-897 Instead of displaying inside "Customer Parts" => "No results found. Please try later again." I suggest du change the message, since "try later again" should be used if the IF is failing. I am guessing in this scenario that there are no data created; so would be good for the user to understand how data can get added

**Comment by ds-mwesener** [comment]
Hi @jjeroch thank you very much for the good feedback. We have directly started in creating issues to make sure that we can implement them ASAP. We also already added the issues to our [Known Knowns](https://github.com/eclipse-tractusx/traceability-foss/releases/tag/11.0.0) section in the release log. 

We try to resolve the blocking issues on highest priority, but kindly ask you for approval of the uux review. 

## User experience
ITEM 1 -> https://github.com/eclipse-tractusx/traceability-foss/issues/989
 
ITEM 2 -> https://github.com/eclipse-tractusx/traceability-foss/issues/990
Might be resolved by https://github.com/eclipse-tractusx/traceability-foss/issues/914 (dashboard rework)
 
ITEM 3 -> https://github.com/eclipse-tractusx/traceability-foss/issues/991
Maybe part of https://github.com/eclipse-tractusx/traceability-foss/issues/908
 
ITEM 4 -> https://github.com/eclipse-tractusx/traceability-foss/issues/992
 
ITEM 5 -> For me it works. Maybe there is confusion because "AsPlanned" table has less columns in general? Also there is already a scrollbar. We will look further if we can find any issue on that one.
 
ITEM 6 -> https://github.com/eclipse-tractusx/traceability-foss/issues/993
 
ITEM 7, 8, 9 -> https://github.com/eclipse-tractusx/traceability-foss/issues/994
 
ITEM 10 -> https://github.com/eclipse-tractusx/traceability-foss/issues/995
 
ITEM 11 -> https://github.com/eclipse-tractusx/traceability-foss/issues/996
 
ITEM 12 -> https://github.com/eclipse-tractusx/traceability-foss/issues/915
For this, there is already a ticket.
 
ITEM 13 -> https://github.com/eclipse-tractusx/traceability-foss/issues/997
 
ITEM 14 -> https://github.com/eclipse-tractusx/traceability-foss/issues/998
 
ITEM 15 -> https://github.com/eclipse-tractusx/traceability-foss/issues/1001
 
## StyleGuide Compliance
ITEM 1 -> https://github.com/eclipse-tractusx/traceability-foss/issues/1001
 
ITEM 2, 3 -> Since we do not have anymore those two tables, this might be an browser caching issue? 
 
ITEM 4 -> https://github.com/eclipse-tractusx/traceability-foss/issues/919
https://github.com/eclipse-tractusx/traceability-foss/issues/913
There are already tickets for this.
 
## Responsiveness
ITEM 1 -> https://github.com/eclipse-tractusx/traceability-foss/issues/999
 
ITEM 2 -> https://github.com/eclipse-tractusx/traceability-foss/issues/787
 
ITEM 3 -> https://github.com/eclipse-tractusx/traceability-foss/issues/1000
I could not replicate it. Will be investigated.

**Comment by cbrugg** [comment]
As we discussed INT Tests were sucessfully rerun yesterday,
However, as I see some Feedback with "Blocking" Issues above can you please outline in how far you plan to address those issues for Release 24.05? Are they blocking in the sense of release hindering? Thank You!

**Comment by vialkoje** [comment]
is there already some feedback on data sovereignty ? QG-Checklist or maybe a successfully passed SovTest ? Am I missing it ?

**Comment by cbrugg** [comment]
@vialkoje Data Sov Tests were performed successfully as referenced in the Ticket above (next to the Data Sov Checkmark).
From Testmanagement perspective I can give my approval as there are only PASSED and N/A.
In how far this substitutes an alignment with you and the Trace X Team I may not say.

**Comment by ds-crehm** [comment]
@cbrugg as Max already mentioned we are working on the blocking UUX topics with highest priority and also added all of the issues to our Known Knowns. We hope that is enough to get an approval of the UUX review.

**Comment by cbrugg** [comment]
Thank you for clarifying!
If @jjeroch approves the topics as Known Knowns then Testmanagement can also give their approval. 
All other tests have passed as mentioned.

**Comment by KMA-2019** [comment]
@vialkoje , @cbrugg , @mkanal as aligned referencing here notes / feedback from **E2E Tests for Data Sovereignty.**
No blocking issues for current Rel 24.05 but main items to be considered for next release(s): 

- Note: **additional tests (from customer perspective) only partially possible**
- specific **usage policies not transparent enough** - in UI for Admin Role: "publish Asset" only shows name of policy, not actual policies, i.e. create contract offer, as well as in contract view (at time of test not working correctly --> planned for 24.08)
- app relies mainly on backend configuration of policies, no UI yet for definition and **maintenance of Company specific Rules**
- concept of **default policy** to be used in case no specific one is available for auto-negotiation should be re-assessed with customer base
- currently no check for traceability specific FrameworkAgreement Constraint, **successfull negotiation with Quality Framework** (align with upcoming changes to Data Exchange Governance by Association / in ORDL Repo)
- **ContractReference Constraint** can be manually added, however not obvious to configure policies specific to ONE partner only 
- in case of non-matching policies (tested in various scenarios) no negotiation takes place but there is not **visualization or specific Error message to user**
- **no validation of the Schema** "profile": "cx-policy:profile2405" (required to ensure interop with other traceability apps) --> planned interface with Policy Hub, requires check of dev dependencies

**Comment by vialkoje** [comment]
> @vialkoje Data Sov Tests were performed successfully as referenced in the Ticket above (next to the Data Sov Checkmark). From Testmanagement perspective I can give my approval as there are only PASSED and N/A. In how far this substitutes an alignment with you and the Trace X Team I may not say.

I'd expect that there is either a written evaluation of the QG-Checklist https://confluence.catena-x.net/x/NTeJBg - which may refer to successfully passed tests or an invitation for an alignment via telco with me to make sure the sovereignty criteria are passed successfully. The Test-cases themself are not sufficient.

**Comment by ds-lcapellino** [comment]
Hi @vialkoje,
Trace-X uses the IRS for EDC communication. Since IRS is compliant to the Dava Sov QGate criteria as seen here (
https://github.com/eclipse-tractusx/sig-release/issues/670#issuecomment-2107616470)
and tested by (https://jira.catena-x.net/browse/TEST-1918?focusedCommentId=83975&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel), I kindly ask for Data Sov approval.

**Comment by cbrugg** [comment]
As discussed in the Daily TM approval is given if UI/UX findings are identified as Known Knowns and adressed in R24.08. Thank you.

**Comment by RolaH1t** [comment]
Hi @ds-crehm and @ds-lcapellino 
I believe @mkanal is unavailable these days - so may I ask you to finally close-out the last items on data sov and documentation of knownknowns?
Pls reach out to a committer to also formally check the boxes on top once completed.
Hope we can fully approve the QG asap

**Comment by ds-lcapellino** [comment]
Hi @RolaH1t,
yes, @mkanal is currently on vacation. 
For the known kowns, we have created a new release, which addresses most of the findings. However, we listed all of them on the release page: https://github.com/eclipse-tractusx/traceability-foss/releases/tag/11.0.1
Regarding data sov, we are currently in contact with @vialkoje. 

@cbrugg, @jjeroch: I kindly ask you for your approval by checking the boxes on the top. 
Thank you very much!

**Comment by ds-lcapellino** [comment]
Hi @cbrugg , @jjeroch ,
Thank you for the feedback. For the new release [11.0.1](https://github.com/eclipse-tractusx/traceability-foss/releases/tag/11.0.1) we worked on the UUX findings with the highest priority. Here you can find the current state of the findings (Also listed in known knowns of the [latest release](https://github.com/eclipse-tractusx/traceability-foss/releases/tag/11.0.1)):
 
**User Experience**
 
ITEM 1 → Done with https://github.com/eclipse-tractusx/traceability-foss/issues/989
 
ITEM 2 → Done with https://github.com/eclipse-tractusx/traceability-foss/issues/914
 
ITEM 3 → Done with https://github.com/eclipse-tractusx/traceability-foss/issues/991
 
ITEM 4 → Done with https://github.com/eclipse-tractusx/traceability-foss/issues/992
 
ITEM 5 → Not replicable, will be investigated
 
ITEM 6 → not blocking, issue existing, will be implemented
 
ITEM 7, 8, 9 → Done with https://github.com/eclipse-tractusx/traceability-foss/issues/994
 
ITEM 10 → Done with https://github.com/eclipse-tractusx/traceability-foss/issues/995
 
ITEM 11 → not blocking, issue existing, will be implemented
 
ITEM 12 → Done with https://github.com/eclipse-tractusx/traceability-foss/issues/915
 
ITEM 13 → Done with https://github.com/eclipse-tractusx/traceability-foss/issues/997
 
ITEM 14 → Done with https://github.com/eclipse-tractusx/traceability-foss/issues/998
 
ITEM 15 → Issue existing, will be conceptualized and implemented
 
**Styleguide Compliance**
 
ITEM 1 → Issue existing, will be conceptualized and implemented
 
ITEM 2 → Done with https://github.com/eclipse-tractusx/traceability-foss/issues/914
 
ITEM 3 → Done with https://github.com/eclipse-tractusx/traceability-foss/issues/914
 
ITEM 4 → Done as part of https://github.com/eclipse-tractusx/traceability-foss/issues/913
 
**Responsiveness**
 
ITEM 1 → Issue existing, will be conceptualized and implemented
 
ITEM 2 → not blocking, will be implemented
 
ITEM 3 → Not replicable, will be investigated
 
We hope that this is sufficient to get your approval. Thank you very much!

**Comment by vialkoje** [comment]
As IRS functionality is used: Configuration of acceptable policies in the IRS has to be communicated to the consuming entity - along with the fact to arbitrarily chose the first acceptable offer if multiple exist. Please point me to the documentation where this is described. Technically everything is implemented. Expert approval granted.

**Comment by cbrugg** [comment]
Thank you @ds-lcapellino as written above Testmanagement approval is hereby given as the issues are adressed as known knowns.

**Comment by ds-lcapellino** [comment]
Thank you for your feedback @vialkoje @cbrugg. We will update the checkboxes in the description accordingly. 
I've created https://github.com/eclipse-tractusx/traceability-foss/issues/1007 to address the data sov aspects in Trace-X and the things @vialkoje pointed out. 
Thanks to everyone!

**Comment by jjeroch** [comment]
> Hi @cbrugg , @jjeroch , Thank you for the feedback. For the new release [11.0.1](https://github.com/eclipse-tractusx/traceability-foss/releases/tag/11.0.1) we worked on the UUX findings with the highest priority. Here you can find the current state of the findings (Also listed in known knowns of the [latest release](https://github.com/eclipse-tractusx/traceability-foss/releases/tag/11.0.1)):
> 
> **User Experience**
> 
> ITEM 1 → Done with [eclipse-tractusx/traceability-foss#989](https://github.com/eclipse-tractusx/traceability-foss/issues/989)
> 
> ITEM 2 → Done with [eclipse-tractusx/traceability-foss#914](https://github.com/eclipse-tractusx/traceability-foss/issues/914)
> 
> ITEM 3 → Done with [eclipse-tractusx/traceability-foss#991](https://github.com/eclipse-tractusx/traceability-foss/issues/991)
> 
> ITEM 4 → Done with [eclipse-tractusx/traceability-foss#992](https://github.com/eclipse-tractusx/traceability-foss/issues/992)
> 
> ITEM 5 → Not replicable, will be investigated
> 
> ITEM 6 → not blocking, issue existing, will be implemented
> 
> ITEM 7, 8, 9 → Done with [eclipse-tractusx/traceability-foss#994](https://github.com/eclipse-tractusx/traceability-foss/issues/994)
> 
> ITEM 10 → Done with [eclipse-tractusx/traceability-foss#995](https://github.com/eclipse-tractusx/traceability-foss/issues/995)
> 
> ITEM 11 → not blocking, issue existing, will be implemented
> 
> ITEM 12 → Done with [eclipse-tractusx/traceability-foss#915](https://github.com/eclipse-tractusx/traceability-foss/issues/915)
> 
> ITEM 13 → Done with [eclipse-tractusx/traceability-foss#997](https://github.com/eclipse-tractusx/traceability-foss/issues/997)
> 
> ITEM 14 → Done with [eclipse-tractusx/traceability-foss#998](https://github.com/eclipse-tractusx/traceability-foss/issues/998)
> 
> ITEM 15 → Issue existing, will be conceptualized and implemented
> 
> **Styleguide Compliance**
> 
> ITEM 1 → Issue existing, will be conceptualized and implemented
> 
> ITEM 2 → Done with [eclipse-tractusx/traceability-foss#914](https://github.com/eclipse-tractusx/traceability-foss/issues/914)
> 
> ITEM 3 → Done with [eclipse-tractusx/traceability-foss#914](https://github.com/eclipse-tractusx/traceability-foss/issues/914)
> 
> ITEM 4 → Done as part of [eclipse-tractusx/traceability-foss#913](https://github.com/eclipse-tractusx/traceability-foss/issues/913)
> 
> **Responsiveness**
> 
> ITEM 1 → Issue existing, will be conceptualized and implemented
> 
> ITEM 2 → not blocking, will be implemented
> 
> ITEM 3 → Not replicable, will be investigated
> 
> We hope that this is sufficient to get your approval. Thank you very much!

Hi @ds-lcapellino thanks a lot. Can you please share a trace-x version where the fixes can get tested.

**Comment by ds-mwesener** [comment]
Hi @jjeroch it is included in the latest release [11.0.1](https://github.com/eclipse-tractusx/traceability-foss/releases/tag/11.0.1) of trace-x and deployed on: 

https://traceability-portal-int-a.int.demo.catena-x.net

Please use your own user and realm: BMW.

If you have any questions please let me know.

Thanks in advance.

Kind regards

**Comment by KMA-2019** [comment]
Hi @ds-mwesener, @ds-lcapellino, @mkanal, cc: @jjeroch 
Regarding UUX findings please see the retest results: 

**All items not mentioned below have been retested successfully. Thanks!** 
Note: User Experience, **ITEM 5** – blocking - Scroll Bar now existing, **can also be closed** 

**Still open are the following. 
@jjeroch can you please review and decide about granting final approval. ** 

**_User Experience_**

ITEM 6 – not blocking - issue existing, will be investigated [eclipse-tractusx/traceability-foss#993](https://github.com/eclipse-tractusx/traceability-foss/issues/993)

- **ITEM 9 – blocking - no change for user. Still there is no option to edit/change and hence the Icon and Counter do not make sense to the user.**

ITEM 11 – not blocking - issue existing, will be implemented [eclipse-tractusx/traceability-foss#996](https://github.com/eclipse-tractusx/traceability-foss/issues/996)

- **ITEM 12 – blocking - has been updated, Thanks. Noticed, though, that HELP is missing Section for “Administration -> BPN – EDC Configuration”**

-  **!! ITEM 13 – blocking – thanks for providing more test data. Now multiple Policies are available. However, still cannot see relevant policy details. !!**

![image](https://github.com/eclipse-tractusx/sig-release/assets/60438746/f1f98b28-8daf-48c9-bdb4-1d3bddfd72cf)


ITEM 15 – blocking - Issue existing, will be conceptualized and implemented [eclipse-tractusx/traceability-foss#1001](https://github.com/eclipse-tractusx/traceability-foss/issues/1001)

**_Styleguide Compliance_** 

ITEM 1 – blocking - Issue existing, will be conceptualized and implemented [eclipse-tractusx/traceability-foss#1001](https://github.com/eclipse-tractusx/traceability-foss/issues/1001)

- **ITEM 2 – blocking - Information of Record Numbers available. However, frame still missing (see out of scope in https://github.com/eclipse-tractusx/traceability-foss/issues/914) , “View All” Button is now completely disabled and not only when table is empty or few entries.**

- **ITEM 3 – blocking – see ITEM 2 for different table**

_**Responsiveness**_ 

ITEM 1 – blocking - Issue existing, will be conceptualized and implemented [eclipse-tractusx/traceability-foss#999](https://github.com/eclipse-tractusx/traceability-foss/issues/999)
ITEM 2 – not blocking - will be implemented [eclipse-tractusx/traceability-foss#787](https://github.com/eclipse-tractusx/traceability-foss/issues/787)
ITEM 3 – blocking - not replicable, will be investigated [eclipse-tractusx/traceability-foss#1000](https://github.com/eclipse-tractusx/traceability-foss/issues/1000)

_**Old comments (leftovers)**_ 

o TRACEFOSS-897 (and moved to https://github.com/eclipse-tractusx/traceability-foss/issues/491)

**- @ds-mwesener Can you please comment on these two items?**

**Comment by jjeroch** [comment]
UI/UX Findings existing, still gateway approved with documentation of findings inside the changeLogs under KnownKnowns

**Comment by RolaH1t** [comment]
@almadigabor may I ask you to complete the final checkbox on top, so QG can be approved? THX

**Comment by almadigabor** [comment]
Hey @RolaH1t, do you mean the "UUX Checks Compliant with the Style Guide" box? That's the only unchecked box I see. I can mark it, though I don't really know the process behind.

**Comment by RolaH1t** [comment]
yes, please => that`s the one
Currently there is not (yet) a process behind, because the relevant TRG is still in draft => but pls refer to @jjeroch `s comment this morning (see above)

**Comment by RolaH1t** [comment]
Congrats:
Quality Gate fully approved with all necessary pre-requisites fulfilled!
Thanks for all your efforts,
Roland

**Comment by ds-mwesener** [comment]
> Congrats: Quality Gate fully approved with all necessary pre-requisites fulfilled! Thanks for all your efforts, Roland

Thank you very much! We appreciate it!

**Comment by stephanbcbauer** [comment]
Hello @mkanal  

Since the feature is a 24.05 feature and the development phase for 24.08 is coming to an end, we need a status on the feature. Can you please update the status?

- [ ] Currently you are assigned (Responsible) → Is this correct? If not, please assign the correct contact person
- [ ] Please check whether the status (backlog, work in progress ...) is set correctly
- [ ] Please comment on the current status of the feature
- [ ] Are all SubTasks (issues from other repositories that deal with the feature) linked? → The easiest way is to mention the feature here in the issue (via the ID) so we can see which teams/repositories are involved.
- [ ] Is there a spillover planned?

If you need any clarification, please get in touch, thank you very much.

Stephan

**Comment by mkanal** [comment]
"Congrats:
Quality Gate fully approved with all necessary pre-requisites fulfilled!
Thanks for all your efforts,
Roland" 
Ticket will be set as done and set to close.
