### ISSUE TITLE
EDC - Concept for a Connector Testbed/ Test-KIT

### ISSUE THREAD

**Issue by stefan-ettl** [eclipse-tractusx/sig-release#612]
As a developer of a custom Connector,
As a developer with the intention to highly customize the existing EDC,

I want to test if my custom Connector is interoperable and usable within the Catena-X Dataspace. 

In Scope is "only" the wire-level, like DSP and IATP.

Therefore a Testbed/ TestKIT is needed.

A first step towards a TestKIT has already been taken by the Upstream TCK (https://projects.eclipse.org/projects/technology.dataspacetck) project. However some steps towards a usable Catena-X solution are still missing.
With this feature, we want to prepare an implementation of a Catena-X Connector Testbed and close the Gap between the Upstream TCK and Catena-X requirements. 

- [ ] Create a list of Catena-X requirements in regards to a Testbed.
- [ ] Evaluate the TCK in regards to those requirements and document possible gaps.
- [ ] Document and prepare follow up tasks to create a Testbed on base of the TCK.

**Comment by stephanbcbauer** [comment]
Hello @stefan-ettl , @jimmarino 

Since the feature is a 24.08 feature and the development phase is coming to an end, we need a status on the feature.

- [ ] Currently you are assigned (Responsible) → Is this correct? If not, please assign the correct contact person
- [ ] Please check whether the status (backlog, work in progress ...) is set correctly
- [ ] Please check whether there is an assignment to a committee or expert group (supported-by) to be found on the [board](https://github.com/orgs/eclipse-tractusx/projects/26/views/28)
- [ ] Please comment on the current status of the feature
- [ ] Are all SubTasks (issues from other repositories that deal with the feature) linked? → The easiest way is to mention the feature here in the issue (via the ID) so we can see which teams/repositories are involved.

If you need any clarification, please get in touch, thank you very much.
Stephan

**Comment by lgblaumeiser** [comment]
2024-06-11: Work in the upstream TCK is going on. It is expected, that this fulfills the requirements. A check will be executed at the end of current activities.

**Comment by lgblaumeiser** [comment]
2024-06-11:

* [x]  Currently you are assigned (Responsible) → Is this correct? If not, please assign the correct contact person
* [x]  Please check whether the status (backlog, work in progress ...) is set correctly
* [x]  Please check whether there is an assignment to a committee or expert group (supported-by) to be found on the [board](https://github.com/orgs/eclipse-tractusx/projects/26/views/28)
* [x]  Please comment on the current status of the feature: see comment above
* [ ]  Are all SubTasks (issues from other repositories that deal with the feature) linked? → The easiest way is to mention the feature here in the issue (via the ID) so we can see which teams/repositories are involved.
        @jimmarino: Please link the work items related to this feature to the issue.

**Comment by lgblaumeiser** [comment]
Dependecy to upstream, work is therefore ongoing. Could be a spill over of 24/08.

**Comment by jimmarino** [comment]
Just completed a write-up/concept for what this entails on the C-X side:

https://github.com/eclipse-tractusx/tractusx-profiles/blob/main/cx/tck/tck.assertions.md
