### ISSUE TITLE
Update Circularity KIT R24.08

### ISSUE THREAD

**Issue by LuisRickert** [eclipse-tractusx/sig-release#614]
## Description
As for now we are still waiting for the release of the EDC Version 0.7, there may be changes which require us to adjust the KITs content.

## Impact
This has only impact on the KIT since we are adjusting the KITs content to the newest release

[PR-925](https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/925)

more detailed Issue [Issue](https://github.com/eclipse-tractusx/sig-release/issues/703)

## Additional information 

- [x] I'm willing to contribute to this feature

**Comment by LuisRickert** [comment]
This was a duplicate to the [issue 591](https://github.com/eclipse-tractusx/sig-release/issues/591)

**Comment by stephanbcbauer** [comment]
Was presented in the open planning ⇾ valid work.

**Comment by stephanbcbauer** [comment]
Hello @LuisRickert ,

since the feature is a 24.08 feature and the development phase is coming to an end, we need a status on the feature.

- [ ] Currently you are assigned (Responsible) → Is this correct? If not, please assign the correct contact person
- [ ] Please check whether the status (backlog, work in progress ...) is set correctly
- [ ] Please check whether there is an assignment to a committee or expert group (supported-by) to be found on the [board](https://github.com/orgs/eclipse-tractusx/projects/26/views/28)
- [ ] Please comment on the current status of the feature
- [ ] Are all SubTasks (issues from other repositories that deal with the feature) linked? → The easiest way is to mention the feature here in the issue (via the ID) so we can see which teams/repositories are involved.

If you need any clarification, please get in touch, thank you very much.
Stephan

**Comment by stanfaldin** [comment]
Noah Cherny from the Circularity Team has delivered the Update in an .md file that Luis will implement via pull request upon his return on 10.6.

Quote: Alle Unterlagen liegen in [04_UpdateVersion4.0](https://urldefense.com/v3/__https:/bcgcatenax.sharepoint.com/:f:/r/sites/ARTV/Shared*20Documents/Circular*20Economy/13_CE*20Kits/02_Circularity*20Kit/04_UpdateVersion4.0?csf=1&web=1&e=nXCPYh__;JSUlJQ!!OrxsNty6D4my!_FcPqHI8b1dkwaThnKNZhT_vOwG3tNqLA18vT8w0f58G4a7eqyavYS_JTU-H2TxySpR9HA90Uyb1LzqWRjdkNzxvACen2Uk9qIU$)
Die aktuelle md. Datei mit allen Änderungen heißt: 20240506_CircularityKIT_AdoptionVIew

**Comment by stephanbcbauer** [comment]
Hello @LuisRickert  
 
In a few weeks, we want to publish Tractus-X Release 24.08. For this, we need a clear status about the features (which will be included in the release and which will be cancelled or postponed to the next release).
 
Currently, the feature is still in status `Work in progress`. Please update the status by 09.07.24 eob.
 
If the feature is not ready for release 24.08, or it is possibly not planned at all, please set the status to `Not in release`. Please remember that in this case, any dependent components must be informed.
 
Thank you and best regards.

**Comment by LuisRickert** [comment]
added related PR

**Comment by LuisRickert** [comment]
this is a duplicate to [Issue-703](https://github.com/eclipse-tractusx/sig-release/issues/703)
