### ISSUE TITLE
EDC - Architecture Documentation

### ISSUE THREAD

**Issue by lgblaumeiser** [eclipse-tractusx/sig-release#617]
## Description

As an EDC stakeholder,

I want to have an easy way to understand basic concepts of the EDC and I need a map to trace certain features to their implementation.

For that an architecture document should be started that gives a structural overview of the components that build up an EDC and describes general mechanisms like the extension mechanism.

- [ ] An analysis of existing documentation is done and input is gathered
- [ ] Major stakeholders in the development team are asked for their input
- [ ] An initial architecture document is created and agreed by the developer community

## Impact

None, as this is pure documentation

## Additional information 

- [x] I'm willing to contribute to this feature

**Comment by stephanbcbauer** [comment]
was presented in open planning ⇾ developer and committer are involved

**Comment by stephanbcbauer** [comment]
Hello @lgblaumeiser  

Since the feature is a 24.08 feature and the development phase is coming to an end, we need a status on the feature.

- [ ] Currently you are assigned (Responsible) → Is this correct? If not, please assign the correct contact person
- [ ] Please check whether the status (backlog, work in progress ...) is set correctly
- [ ] Please check whether there is an assignment to a committee or expert group (supported-by) to be found on the [board](https://github.com/orgs/eclipse-tractusx/projects/26/views/28)
- [ ] Please comment on the current status of the feature
- [ ] Are all SubTasks (issues from other repositories that deal with the feature) linked? → The easiest way is to mention the feature here in the issue (via the ID) so we can see which teams/repositories are involved.

If you need any clarification, please get in touch, thank you very much.
Stephan

**Comment by lgblaumeiser** [comment]
2024-06-11: In Progress, currently no heavy activity

**Comment by lgblaumeiser** [comment]
2024-06-11:

* [x]  Currently you are assigned (Responsible) → Is this correct? If not, please assign the correct contact person
* [x]  Please check whether the status (backlog, work in progress ...) is set correctly
* [x]  Please check whether there is an assignment to a committee or expert group (supported-by) to be found on the [board](https://github.com/orgs/eclipse-tractusx/projects/26/views/28)
* [x]  Please comment on the current status of the feature:
         In Progress, currently no heavy activity
* [x]  Are all SubTasks (issues from other repositories that deal with the feature) linked? → The easiest way is to mention the feature here in the issue (via the ID) so we can see which teams/repositories are involved.

**Comment by lgblaumeiser** [comment]
Spillover for next release

**Comment by stephanbcbauer** [comment]
Presented in the DRAFT Feature Freeze -> Committer is available

**Comment by lgblaumeiser** [comment]
De-Prioritized and closed

**Comment by stephanbcbauer** [comment]
Issue already closed -> new status DONE
