### ISSUE TITLE
EDC - Protocol Maintenance

### ISSUE THREAD

**Issue by lgblaumeiser** [eclipse-tractusx/sig-release#620]
## Description

As an EDC user,

I want to use an EDC service, that is compatible to the current DSP and IATP protocol version

Therefore, with the DSP and IATP standardization effort starting, we will need to allocate time to tracking spec changes, bug fixing, and ensuring interoperability.

- [ ] Gaps between the current protocol version defined in the Eclipse Dataspace Working Group are identified and documented as an issue
- [ ] Measures are taken to close the identified gaps

Initial creator: @jimmarino 

## Impact

Depending on the protocol changes, the impact might be breaking. If so, special measures need to be discussed in order to give clear guidance to EDC users, on how to deal with the protocol changes, or to implement the changes in a way, that they are non-breaking during use.
 
## Additional information 

- [ ] I'm willing to contribute to this feature

**Comment by stephanbcbauer** [comment]
was presented in the open planning ⇾ contributors and committer are involved.

**Comment by stephanbcbauer** [comment]
Hello @jimmarino, @lgblaumeiser 

Since the feature is a 24.08 feature and the development phase is coming to an end, we need a status on the feature.

- [ ] Currently you are assigned (Responsible) → Is this correct? If not, please assign the correct contact person
- [ ] Please check whether the status (backlog, work in progress ...) is set correctly
- [ ] Please check whether there is an assignment to a committee or expert group (supported-by) to be found on the [board](https://github.com/orgs/eclipse-tractusx/projects/26/views/28)
- [ ] Please comment on the current status of the feature
- [ ] Are all SubTasks (issues from other repositories that deal with the feature) linked? → The easiest way is to mention the feature here in the issue (via the ID) so we can see which teams/repositories are involved.

If you need any clarification, please get in touch, thank you very much.
Stephan

**Comment by lgblaumeiser** [comment]
2024-06-11: Close the issue, as there is no change to be expected, that will make it into 24.08.

**Comment by lgblaumeiser** [comment]
2024-06-11:

* [x]  Currently you are assigned (Responsible) → Is this correct? If not, please assign the correct contact person
* [x]  Please check whether the status (backlog, work in progress ...) is set correctly
* [x]  Please check whether there is an assignment to a committee or expert group (supported-by) to be found on the [board](https://github.com/orgs/eclipse-tractusx/projects/26/views/28)
* [x]  Please comment on the current status of the feature:
          Issue is closed, as there is no change to be expected, that will make it into 24.08.
* [x]  Are all SubTasks (issues from other repositories that deal with the feature) linked? → The easiest way is to mention the feature here in the issue (via the ID) so we can see which teams/repositories are involved.
