### ISSUE TITLE
EDC - Follow-Up Guidance for archiving of Metadata

### ISSUE THREAD

**Issue by stefan-ettl** [eclipse-tractusx/sig-release#621]
As an EDC Operator I want to know how to safely archive Metadata (Assets, Policies, ...)

Follow-Up Issue.

- [ ]  Concept/ Idea/ Guide for archiving Metadata has been created.

![Image](https://github.com/eclipse-tractusx/sig-release/assets/72562218/45f221e0-baad-41eb-b517-435cdc81f44f)

**Comment by stephanbcbauer** [comment]
Was presented in open planning ⇾ contributors and committer are involved.

**Comment by stephanbcbauer** [comment]
Hello @stefan-ettl , @saschaisele-zf , @lgblaumeiser  

Since the feature is a 24.08 feature and the development phase is coming to an end, we need a status on the feature.

- [ ] Currently you are assigned (Responsible) → Is this correct? If not, please assign the correct contact person
- [ ] Please check whether the status (backlog, work in progress ...) is set correctly
- [ ] Please check whether there is an assignment to a committee or expert group (supported-by) to be found on the [board](https://github.com/orgs/eclipse-tractusx/projects/26/views/28)
- [ ] Please comment on the current status of the feature
- [ ] Are all SubTasks (issues from other repositories that deal with the feature) linked? → The easiest way is to mention the feature here in the issue (via the ID) so we can see which teams/repositories are involved.

If you need any clarification, please get in touch, thank you very much.
Stephan

**Comment by saschaisele-zf** [comment]
Current progress has stalled in concert with this [discussion](https://github.com/eclipse-tractusx/tractusx-edc/discussions/1049).
Since there has been no further input,  the next step would be writing a decision record with what we have.

**Comment by lgblaumeiser** [comment]
2024-06-11:
 
* [x]  Currently you are assigned (Responsible) → Is this correct? If not, please assign the correct contact person
* [x]  Please check whether the status (backlog, work in progress ...) is set correctly
* [x]  Please check whether there is an assignment to a committee or expert group (supported-by) to be found on the [board](https://github.com/orgs/eclipse-tractusx/projects/26/views/28)
* [x]  Please comment on the current status of the feature: see above
* [x]  Are all SubTasks (issues from other repositories that deal with the feature) linked? → The easiest way is to mention the feature here in the issue (via the ID) so we can see which teams/repositories are involved.
