### ISSUE TITLE
EDC - Concept for Management Domains

### ISSUE THREAD

**Issue by stefan-ettl** [eclipse-tractusx/sig-release#622]
As a large company, I want to separate different aspects by working with an EDC regarding to the respective department.

Upstream EDC Support distributed deployment scenarios where an organization may have different departments that manage specific sets of assets for data sharing.

- [ ] Concept/ Idea about Management Domains has been created.

Initial creator: @jimmarino

**Comment by stephanbcbauer** [comment]
Was presented in open planning ⇾ contributors and committer are involved

**Comment by stephanbcbauer** [comment]
Hello @stefan-ettl , @jimmarino  

Since the feature is a 24.08 feature and the development phase is coming to an end, we need a status on the feature.

- [ ] Currently you are assigned (Responsible) → Is this correct? If not, please assign the correct contact person
- [ ] Please check whether the status (backlog, work in progress ...) is set correctly
- [ ] Please check whether there is an assignment to a committee or expert group (supported-by) to be found on the [board](https://github.com/orgs/eclipse-tractusx/projects/26/views/28)
- [ ] Please comment on the current status of the feature
- [ ] Are all SubTasks (issues from other repositories that deal with the feature) linked? → The easiest way is to mention the feature here in the issue (via the ID) so we can see which teams/repositories are involved.

If you need any clarification, please get in touch, thank you very much.
Stephan

**Comment by jimmarino** [comment]
In the pipeline...

**Comment by lgblaumeiser** [comment]
2024-06-11: Draft about to be proposed.

**Comment by lgblaumeiser** [comment]
2024-06-11:

* [x]  Currently you are assigned (Responsible) → Is this correct? If not, please assign the correct contact person
* [x]  Please check whether the status (backlog, work in progress ...) is set correctly
* [x]  Please check whether there is an assignment to a committee or expert group (supported-by) to be found on the [board](https://github.com/orgs/eclipse-tractusx/projects/26/views/28)
* [x]  Please comment on the current status of the feature:
         Draft about to be proposed.
* [ ]  Are all SubTasks (issues from other repositories that deal with the feature) linked? → The easiest way is to mention the feature here in the issue (via the ID) so we can see which teams/repositories are involved.
        @jimmarino : Please add a link to the upstream issues or PRs as soon as they exist

**Comment by lgblaumeiser** [comment]
Result: https://github.com/eclipse-edc/Connector/blob/main/docs/developer/management-domains/management-domains.md

**Comment by DanielaWuensch** [comment]
Please consider in this issue the following scenario as well:
**Scenario:** A data provider operates multiple EDC connectors and data catalogs

**Problem:** If a data consumer is unaware of which EDC holds the desired offer, he needs to iterate over all catalogs, that's quite inefficient.

**Proposed solution:** There should be a concept to manage multiple EDCs to federate their catalogs and expose them in a unified manner. Configured restrictions to offers in one EDC must be reflected in a federators behavior.

**Impacted components**
- Upstream EDC
- DSP for get catalogue?
- CX-0018?

**Comment by jimmarino** [comment]
> Please consider in this issue the following scenario as well: **Scenario:** A data provider operates multiple EDC connectors and data catalogs
> 
> **Problem:** If a data consumer is unaware of which EDC holds the desired offer, he needs to iterate over all catalogs, that's quite inefficient.
> 
> **Proposed solution:** There should be a concept to manage multiple EDCs to federate their catalogs and expose them in a unified manner. Configured restrictions to offers in one EDC must be reflected in a federators behavior.
> 
> **Impacted components**
> 
> * Upstream EDC
> * DSP for get catalogue?
> * CX-0018?

These scenarios are all defined and handled in the [Management Domains architecture document](https://github.com/eclipse-edc/Connector/blob/main/docs/developer/management-domains/management-domains.md).
