### ISSUE TITLE
EDC - Cleanup Upstream - Transfer Formats

### ISSUE THREAD

**Issue by stefan-ettl** [eclipse-tractusx/sig-release#623]
Upstream EDC Support different transfer format combinations that influence data plane selection. For example, a data plane may support only specific transfer formats. This is a significant amount of work.

- [ ] Cleanup Tasks in Upstream Done. Issue in Upstream: https://github.com/eclipse-edc/Connector/issues/4031

Initial creator: @jimmarino

**Comment by jjeroch** [comment]
@stefan-ettl  can you specifiy the actual task within this feature?

**Comment by stephanbcbauer** [comment]
Was presented in open planning ⇾ contributors and committer are involved

**Comment by stephanbcbauer** [comment]
Hello @stefan-ettl , @ndr-brt , @lgblaumeiser  

Since the feature is a 24.08 feature and the development phase is coming to an end, we need a status on the feature.

- [ ] Currently you are assigned (Responsible) → Is this correct? If not, please assign the correct contact person
- [ ] Please check whether the status (backlog, work in progress ...) is set correctly
- [ ] Please check whether there is an assignment to a committee or expert group (supported-by) to be found on the [board](https://github.com/orgs/eclipse-tractusx/projects/26/views/28)
- [ ] Please comment on the current status of the feature
- [ ] Are all SubTasks (issues from other repositories that deal with the feature) linked? → The easiest way is to mention the feature here in the issue (via the ID) so we can see which teams/repositories are involved.

If you need any clarification, please get in touch, thank you very much.
Stephan

**Comment by ndr-brt** [comment]
The status of this feature is tracked by the story: https://github.com/eclipse-edc/Connector/issues/4031
Pretty much toward the end, one PR is under review and there's one task missing that will be done after the mentioned PR will be merged

**Comment by lgblaumeiser** [comment]
2024-06-11: In addition to @ndr-brt comment:

- [x] Please check whether there is an assignment to a committee or expert group (supported-by) to be found on the [board](https://github.com/orgs/eclipse-tractusx/projects/26/views/28)
