### ISSUE TITLE
EDC - Create Guidance about CatalogCrawler Distribution

### ISSUE THREAD

**Issue by stefan-ettl** [eclipse-tractusx/sig-release#625]
Many end-users and downstream projects are unaware of the EDC Catalog Crawler or how to execute catalog queries. Create a TX distribution for the Catalog Crawler to facilitate its use.

- [ ] Documentation about the Catalog Crawler in regards to TX EDC.
- [ ] Concept/Idea for a possible Distribution has been created. 

Initial creator: @jimmarino

**Comment by matbmoser** [comment]
An idea here would be to include a use case example with the Decentral Digital Twin Registry. An idea would be to include it in the Connector KIT or in the Digital Twin KIT.... The crawler can really help to "manage" the contracts and speed up the catalog and contract negotiation for different use cases in Catena.X. Maybe an idea would be to use the EDC Discovery to get the EDCs related to the company and then keep the catalog updated. We from the digital product pass team have solved in this way: https://github.com/eclipse-tractusx/digital-product-pass/blob/main/docs/data%20retrieval%20guide/DataRetrievalGuide.md

**Comment by stephanbcbauer** [comment]
Hello @stefan-ettl, @jimmarino, @wolf4ood, @lgblaumeiser 

Since the feature is a 24.08 feature and the development phase is coming to an end, we need a status on the feature.

- [ ] Currently you are assigned (Responsible) → Is this correct? If not, please assign the correct contact person
- [ ] Please check whether the status (backlog, work in progress ...) is set correctly
- [ ] Please check whether there is an assignment to a committee or expert group (supported-by) to be found on the [board](https://github.com/orgs/eclipse-tractusx/projects/26/views/28)
- [ ] Please comment on the current status of the feature
- [ ] Are all SubTasks (issues from other repositories that deal with the feature) linked? → The easiest way is to mention the feature here in the issue (via the ID) so we can see which teams/repositories are involved.

If you need any clarification, please get in touch, thank you very much.
Stephan

**Comment by lgblaumeiser** [comment]
2024-06-11: In Progress

**Comment by lgblaumeiser** [comment]
2024-06-11:
 
> * [x]  Currently you are assigned (Responsible) → Is this correct? If not, please assign the correct contact person
> * [x]  Please check whether the status (backlog, work in progress ...) is set correctly
> * [x]  Please check whether there is an assignment to a committee or expert group (supported-by) to be found on the [board](https://github.com/orgs/eclipse-tractusx/projects/26/views/28)
> * [x]  Please comment on the current status of the feature: In Progress
> * [ ]  Are all SubTasks (issues from other repositories that deal with the feature) linked? → The easiest way is to mention the feature here in the issue (via the ID) so we can see which teams/repositories are involved.
            @jimmarino : Please add the link to the issues/PR to the item.

**Comment by lgblaumeiser** [comment]
Postponed to 24/12 because more preparation needs to be done to get this into the connector distribution.

**Comment by stephanbcbauer** [comment]
Hello @lgblaumeiser , @jimmarino , @wolf4ood  
 
In a few weeks, we want to publish Tractus-X Release 24.08. For this, we need a clear status about the features (which will be included in the release and which will be cancelled or postponed to the next release).
 
Currently, the feature is still in status `Backlog`. Please update the status by 09.07.24 eob.
 
If the feature is not ready for release 24.08, or it is possibly not planned at all, please set the status to `Not in release`. Please remember that in this case, any dependent components must be informed.
 
Thank you and best regards.
