### ISSUE TITLE
EDC - Upgrade VC Suite for SSI

### ISSUE THREAD

**Issue by stefan-ettl** [eclipse-tractusx/sig-release#626]
The library we use for handling LDP-VCs had a major upgrade with lots of breaking changes. We either should adapt the code base or roll our own. https://github.com/eclipse-edc/Connector/issues/4066
No "Breaking Change" to the Tractus-X EDC but obviously its impacted under the hood.

- [ ] Upstream Issue/ Upgrade has been completed.

Initial Creator: @paullatzelsperger

**Comment by stephanbcbauer** [comment]
was presented in open planning ⇾ developer and committer are involved

**Comment by lgblaumeiser** [comment]
Done

**Comment by stephanbcbauer** [comment]
Hello @stefan-ettl, @lgblaumeiser 

Since the feature is a 24.08 feature and the development phase is coming to an end, we need a status on the feature.

- [ ] Currently you are assigned (Responsible) → Is this correct? If not, please assign the correct contact person
- [ ] Please check whether the status (backlog, work in progress ...) is set correctly
- [ ] Please check whether there is an assignment to a committee or expert group (supported-by) to be found on the [board](https://github.com/orgs/eclipse-tractusx/projects/26/views/28)
- [ ] Please comment on the current status of the feature
- [ ] Are all SubTasks (issues from other repositories that deal with the feature) linked? → The easiest way is to mention the feature here in the issue (via the ID) so we can see which teams/repositories are involved.

If you need any clarification, please get in touch, thank you very much.
Stephan

**Comment by lgblaumeiser** [comment]
2024-06-11:

* [x]  Currently you are assigned (Responsible) → Is this correct? If not, please assign the correct contact person
* [x]  Please check whether the status (backlog, work in progress ...) is set correctly
* [x]  Please check whether there is an assignment to a committee or expert group (supported-by) to be found on the [board](https://github.com/orgs/eclipse-tractusx/projects/26/views/28)
* [x]  Please comment on the current status of the feature - Done
* [ ]  Are all SubTasks (issues from other repositories that deal with the feature) linked? → The easiest way is to mention the feature here in the issue (via the ID) so we can see which teams/repositories are involved.
        @paullatzelsperger : Please add the link to the PR to the item.

**Comment by paullatzelsperger** [comment]
this was resolved upstream in this PR: https://github.com/eclipse-edc/Connector/pull/4125
