### ISSUE TITLE
Informational Requirements at Dismantling to enable Reuse & Remanufacturing - Whitepaper

### ISSUE THREAD

**Issue by florianstern** [eclipse-tractusx/sig-release#632]
## Description

The Whitepaper will give an overview what information is needed at dismantling of an ELV to enable reuse or reman for its parts. This can also include other form preserving R-strategies (e.g. Repair, Refurb). Such information can be economic, technical, regulatory or environmental (e.g. PCF). The overall goal of this whitepaper is to determine what data a dismantler needs to receive the necessary information and to identify stakeholders within the automotive supply chain, which are able to provide this data. Based on this whitepaper use case standards will be developed as an iterative future step.

Corresponding author: Florian Stern (BMW), florian.stern@bmw.de
Participants: Christoph Schuch (Bosch), Jean-Baptiste Prono (Valeo), Janine Mügge (Fraunhofer IPK), Noah Czorny (Fraunhofer IPK), Matthias Hummel (KUMAsoft), Sophie Smolka (LRP), Christiane Grünewald (TÜV SÜD)

## Impact

The whitepaper could be added to the Circularity KIT.

## Additional information 

- [x] I'm willing to contribute to this feature

**Comment by stephanbcbauer** [comment]
Was presented in the open planning ⇾ responsible committers are already defined

**Comment by stephanbcbauer** [comment]
Hello @florianstern,

Since the feature is a 24.08 feature and the development phase is coming to an end, we need a status on the feature.

- [ ] Currently you are assigned (Responsible) → Is this correct? If not, please assign the correct contact person
- [ ] Please check whether the status (backlog, work in progress ...) is set correctly
- [ ] Please check whether there is an assignment to a committee or expert group (supported-by) to be found on the [board](https://github.com/orgs/eclipse-tractusx/projects/26/views/28)
- [ ] Please comment on the current status of the feature
- [ ] Are all SubTasks (issues from other repositories that deal with the feature) linked? → The easiest way is to mention the feature here in the issue (via the ID) so we can see which teams/repositories are involved.

If you need any clarification, please get in touch, thank you very much.
Stephan

**Comment by florianstern** [comment]
Hi @stephanbcbauer , 

current status is content at 85% and writing at 50%. We are certain, we will finish the paper in time. Regarding all other checks, we are fine.

Best regards
Florian

**Comment by stephanbcbauer** [comment]
Hello @florianstern  
 
In a few weeks, we want to publish Tractus-X Release 24.08. For this, we need a clear status about the features (which will be included in the release and which will be cancelled or postponed to the next release).
 
Currently, the feature is still in status `Work in progress`. Please update the status by 09.07.24 eob.
 
If the feature is not ready for release 24.08, or it is possibly not planned at all, please set the status to `Not in release`. Please remember that in this case, any dependent components must be informed.
 
Thank you and best regards.

**Comment by florianstern** [comment]
Hi @stephanbcbauer 

we will release this feature. The whitepaper is finished and already in group internal review. We will create the PR with you on 15th July.

BR
Florian
