### ISSUE TITLE
ESS kit update 24.08

### ISSUE THREAD

**Issue by birgitZF** [eclipse-tractusx/sig-release#638]
## Description

- Feature author defined: Dieter Narres, PO ESS-Incident.
- Currently there is no Catena-X Association working Group available, regarding the ESS Incident Management (only WG Human Rights). Therefore the consortia ESS Team will work on R24.08.
- We will not implement any FOSS nor any other software application for R24.08.
- We do not have any developer team for feature implementation.
- Key Dates & Milestones are defined in the PI#13 Planning of the CX consortium.
- Business value as defined in ESS-KIT

- Dependencies, Interfaces with other products are identified and described on high level (process)

## Why

- We expect new input from the community / potential solution providers; therefore we expect changes/updates regarding ESS-KIT and Standards.
- We want to update our process-description & Data Model

## Additional information 

- [ ] I'm willing to contribute to this feature

**Comment by birgitZF** [comment]
@stanfaldin most of these topics cannot be filled. I will try to contact you offline..

**Comment by DieterZF** [comment]
Hi Stan, as discussed some minutes before:
Why we need an ESS-KIT update for R24.08:

- new solution provider needs to be implemented, because SAP stopped ESS-Team support
- First KickOff with new solution provider will be done latest mid of April
- We expect updates in process description:
           - Clearing Agency Function
           - Tracing Function
           - Interfaces

-  Updates/Changes expected in Data-Model, process description
- Description of POC Pilot-Process new as outcome and will be implemeted in addition

Expected Results:

- Feature desciption is available
- Required enablers are defined and aligned (e.g., Data-Modell, Interfaces, ESS-Incident Research Process)
- Key dates and milestones are defined
- Business value is defined
- Results of Pilot Tests will be availabel
- Accpetance criteria are defined
- Dependencies with other products or issues are identified and categorized (IRS, KA)
- Known riks are properly adressed
- No open questions left
- Possible implementation issues are defined ...

**Comment by stephanbcbauer** [comment]
Was presented in the open planning ⇾ kit, responsible committers are already defined

**Comment by stephanbcbauer** [comment]
Please add more description

**Comment by DieterZF** [comment]
The Consortia ESS Team commits to work on Release 24.08.
Description:
•	Feature author defined: Dieter Narres, PO ESS-Incident. 
•	Currently there is no Catena-X Association working Group available, regarding the ESS Incident Management (only WG Human Rights). Therefore the consortia ESS Team will work on R24.08. 
•	We will not implement any FOSS nor any other software application for R24.08.
•	We do not have any developer team for feature implementation.
•	Key Dates & Milestones are defined in the PI#13 Planning of the CX consortium.
•	Business value as defined in ESS-KIT
•	Dependencies, Interfaces with other products are identified and described on high level (process)

Why:
•	We expect new input from the community / potential solution providers; therefore we expect changes/updates regarding ESS-KIT and Standards.
•	We want to update our process-description & Data Model

**Comment by stephanbcbauer** [comment]
> The Consortia ESS Team commits to work on Release 24.08. Description: • Feature author defined: Dieter Narres, PO ESS-Incident. • Currently there is no Catena-X Association working Group available, regarding the ESS Incident Management (only WG Human Rights). Therefore the consortia ESS Team will work on R24.08. • We will not implement any FOSS nor any other software application for R24.08. • We do not have any developer team for feature implementation. • Key Dates & Milestones are defined in the PI#13 Planning of the CX consortium. • Business value as defined in ESS-KIT • Dependencies, Interfaces with other products are identified and described on high level (process)
> 
> Why: • We expect new input from the community / potential solution providers; therefore we expect changes/updates regarding ESS-KIT and Standards. • We want to update our process-description & Data Model

Updated your feature description and copied your comment

**Comment by stephanbcbauer** [comment]
Was presented in open planning ⇾ contributors are involved

**Comment by stephanbcbauer** [comment]
Hello @DieterZF ,

Since the feature is a 24.08 feature and the development phase is coming to an end, we need a status on the feature.

- [ ] Currently you are assigned (Responsible) → Is this correct? If not, please assign the correct contact person
- [ ] Please check whether the status (backlog, work in progress ...) is set correctly
- [ ] Please check whether there is an assignment to a committee or expert group (supported-by) to be found on the [board](https://github.com/orgs/eclipse-tractusx/projects/26/views/28)
- [ ] Please comment on the current status of the feature
- [ ] Are all SubTasks (issues from other repositories that deal with the feature) linked? → The easiest way is to mention the feature here in the issue (via the ID) so we can see which teams/repositories are involved.

If you need any clarification, please get in touch, thank you very much.
Stephan

**Comment by DieterZF** [comment]
Hallo Stephan
Hallo Stan,

Birgit ist leider noch 2 Wochen in REHA und ich versuche hier das Thema zu lösen.
Leider bin ich mir dem Prozess nicht vertraut und benötige daher ein wenig Hilfe.
Die Fragen kann ich wie folgt beantworten:

  *   Contact Person okay.
  *   Work in progress ist aus meiner Sicht richtig, doch für unser Team ist die Arbeit abgeschlossen. Daher bin ich mir nicht sicher, welchen Status wir hier einsetzen müssen.
  *   Im Board steht „supportet by“ Sus-Committee. Ist korrekt
  *   Der Status wurde von Birgit kommentiert (05.Apr.) und für uns sind die Arbeiten im KIT abgeschlossen. (bis auf Link zu CoC, siehe nachfolgend)
  *   Wir haben einen Link zum ESS „Code of Conduct“. Wir wissen aktuell nicht wo der CoC abgelegt wird. Hier wird ja gerade ein neuer Prozess vom CX-Verein installiert, dass solche Dokumente nicht mehr im Folder „methodological standards“ zu verorten sind. Daher kann ich aktuell den CoC nicht mit dem KIT verlinken.

Viele Grüße
Dieter


Von: Stephan Bauer ***@***.***>
Gesendet: Mittwoch, 5. Juni 2024 08:27
An: eclipse-tractusx/sig-release ***@***.***>
Cc: Narres Dieter ETF FIEA3 ***@***.***>; Mention ***@***.***>
Betreff: Re: [eclipse-tractusx/sig-release] ESS kit update 24.08 (Issue #638)


Hello @DieterZF<https://github.com/DieterZF> ,

Since the feature is a 24.08 feature and the development phase is coming to an end, we need a status on the feature.

  *   [ ] Currently you are assigned (Responsible) → Is this correct? If not, please assign the correct contact person
  *   [ ] Please check whether the status (backlog, work in progress ...) is set correctly
  *   [ ] Please check whether there is an assignment to a committee or expert group (supported-by) to be found on the board<https://github.com/orgs/eclipse-tractusx/projects/26/views/28>
  *   [ ] Please comment on the current status of the feature
  *   [ ] Are all SubTasks (issues from other repositories that deal with the feature) linked? → The easiest way is to mention the feature here in the issue (via the ID) so we can see which teams/repositories are involved.

If you need any clarification, please get in touch, thank you very much.
Stephan

**Comment by birgitZF** [comment]
@stephanbcbauer can you check if everything is fine with our PR https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/946 with updates for 24.8, I will not be available in cw28, thanks Birgit

**Comment by stephanbcbauer** [comment]
> @stephanbcbauer can you check if everything is fine with our PR [eclipse-tractusx/eclipse-tractusx.github.io#946](https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/946) with updates for 24.8, I will not be available in cw28, thanks Birgit

@birgitZF checked the PR... some minor changes are requested. Thx for your effort

**Comment by birgitZF** [comment]
@stephanbcbauer thans for the review, I fixed the issues (hope they are visible for you and not only locally for me - I am never sure if I did it correctly...). One question about documentation view at the very end we use this link 
https://github.com/eclipse-tractusx/ESS_Kit
but it does not go anywhere, can you give a hint how to correct this link?

**Comment by stephanbcbauer** [comment]
@birgitZF Yes, I can see the changes. thank you very much.I will have a look later and also on the link.

**Comment by stephanbcbauer** [comment]
@birgitZF is the link also in the PR? i am not able to find it

**Comment by birgitZF** [comment]
the link is in the already pblished document at the very end, ESS Kit, Documentation,
https://eclipse-tractusx.github.io/docs-kits/next/kits/ESS-Kit/ESS%20Kit%20Documentation

**Comment by stephanbcbauer** [comment]
Hello @birgitZF  
 
In a few weeks, we want to publish Tractus-X Release 24.08. For this, we need a clear status about the features (which will be included in the release and which will be cancelled or postponed to the next release).
 
Currently, the feature is still in status `Work in progress`. Please update the status by 09.07.24 eob.
 
If the feature is not ready for release 24.08, or it is possibly not planned at all, please set the status to `Not in release`. Please remember that in this case, any dependent components must be informed.
 
Thank you and best regards.

**Comment by birgitZF** [comment]
@stephanbcbauer I understand your statement. We are ready for 24.8.
My question is about one link to the ess-kit in git tractus X:
https://github.com/eclipse-tractusx/ESS_Kit

We had put this link in our kit's documentation page but the link does not go anywhere. I guess it is better to just delete this link.
Thx

**Comment by birgitZF** [comment]
> Hello @birgitZF
> 
> In a few weeks, we want to publish Tractus-X Release 24.08. For this, we need a clear status about the features (which will be included in the release and which will be cancelled or postponed to the next release).
> 
> Currently, the feature is still in status `Work in progress`. Please update the status by 09.07.24 eob.
> 
> If the feature is not ready for release 24.08, or it is possibly not planned at all, please set the status to `Not in release`. Please remember that in this case, any dependent components must be informed.
> 
> Thank you and best regards.

@DieterZF and @stephanbcbauer out ess kit is ready for release 24.8. According to Stephan: "Currently, the feature is still in status Work in progress. Please update the status by 09.07.24 eob."
I do not have no edit rights on this issue to change the status. Can one of you change it, please?

**Comment by stanfaldin** [comment]
Hi @jSchuetz88 , when will the non technical standard part be implemented on the website? We have thisfeature that should refer to the CoC from Dieter, but we are missing the link to it cause it cause it is not implemented yet

**Comment by jSchuetz88** [comment]
> Hi @jSchuetz88 , when will the non technical standard part be implemented on the website? We have thisfeature that should refer to the CoC from Dieter, but we are missing the link to it cause it is not implemented yet

Hi @stanfaldin, sorry for the late response. I prepared the links for the EES CoC files. Unfortunatelly I wait for a PR on my own to add the dummy files, but the links will be as follows: 
- for the english version: https://catenax-ev.github.io/docs/next/non-functional-requirements/assets/CX-NFR-ESS-Codex_v.1.0_EN.pdf
- for the german version https://catenax-ev.github.io/docs/next/non-functional-requirements/assets/CX-NFR-ESS-Codex_v.1.0_DE.pdf

**Comment by birgitZF** [comment]
added link in chapter Access & usage policies / code of conduct. Unfortunately the bracket are still displayed even it I tried several formats,  [The Code of Conduct will be published on the Catena-X webpage] (https://catenax-ev.github.io/docs/next/non-functional-requirements/assets/CX-NFR-ESS-Codex_v.1.0_EN.pdf).

**Comment by jSchuetz88** [comment]
Hi @birgitZF and @DieterZF  ,

thank you for all your efforts :), as the PR has been approved and already merged, I changed the status to done.
