### ISSUE TITLE
Knowledge Agent: Maintenance 24.08

### ISSUE THREAD

**Issue by pdrd** [eclipse-tractusx/sig-release#639]
## Description

This issue is **not aiming for new or extended functionalities**, but assuring all changes are implemented, that are required to ensure the compatibility/interoperability with depending components.

The required changes are depending on the features changes of the depending components, selected during the upcoming PI Planning. The full extent of required changes can only be defined, after all other features requests are approved and finalized in the PI Planning.

The preliminary maintenance changes might include:

- Adaptation of changes of depending components (see Dependencies below)
- Adaptation of new release guidelines for 24.08
- Solving upcoming security issues to fullfil acceptance criteria
- Additional maintenance to pass new quality gates

## Required enablers

Depending on the selected feature changes of the PI Planning.

## Business value

As this is not a feature, it does not provide direct business value, but cares for not losing existing business value, by making sure existing business applications will work with the updated components as well.

## Test scenarios

The existing test scenarios shall be passed as expected, as the functional scope of the component is not changed.

## Acceptance criteria

- Ensured compatibility with depending components based on integration/E2E tests
- Security issues are solved
- Quality Gate has to be passed

## Feature estimation

Not yet possible due to the dependency on the PI Planning.

## Developer team

*t.b.d.*

## Dependencies
- [Eclipse Dataspace Connector (EDC)](https://github.com/eclipse-tractusx/tractusx-edc)

**Comment by drcgjung** [comment]
https://github.com/eclipse-tractusx/knowledge-agents/issues/111

**Comment by drcgjung** [comment]
# Story "Maintain/Update Dependencies"

https://github.com/eclipse-tractusx/knowledge-agents/issues/112

**Comment by stephanbcbauer** [comment]
was presented in the open planning ⇾ developer and committer are involved

**Comment by stephanbcbauer** [comment]
Hello @pdrd, 

Since the feature is a 24.08 feature and the development phase is coming to an end, we need a status on the feature.

- [ ] Currently you are assigned (Responsible) → Is this correct? If not, please assign the correct contact person
- [ ] Please check whether the status (backlog, work in progress ...) is set correctly
- [ ] Please check whether there is an assignment to a committee or expert group (supported-by) to be found on the [board](https://github.com/orgs/eclipse-tractusx/projects/26/views/28)
- [ ] Please comment on the current status of the feature
- [ ] Are all SubTasks (issues from other repositories that deal with the feature) linked? → The easiest way is to mention the feature here in the issue (via the ID) so we can see which teams/repositories are involved.

If you need any clarification, please get in touch, thank you very much.
Stephan

**Comment by stephanbcbauer** [comment]
Hello @pdrd  
 
In a few weeks, we want to publish Tractus-X Release 24.08. For this, we need a clear status about the features (which will be included in the release and which will be cancelled or postponed to the next release).
 
Currently, the feature is still in status `Backlog`. Please update the status by 09.07.24 eob.
 
If the feature is not ready for release 24.08, or it is possibly not planned at all, please set the status to `Not in release`. Please remember that in this case, any dependent components must be informed.
 
Thank you and best regards.

**Comment by stephanbcbauer** [comment]
@TomBuchertTSystems , @pdrd , @drcgjung  This was a feature for milestone 24.08. Is this an ongoing topic? Is it closed? Moved?
