### ISSUE TITLE
Credential Issuance and Identity Wallet Integration Wrapper

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/sig-release#647]
#### Summary:
The objective of this ticket is to create a wrapper that abstracts the complexity of interacting with two separate endpoints for storing and signing credentials in the identity wallet. The wrapper will provide a unified interface to the portal, which will interact with a single endpoint to perform the operations that are currently handled by 'store credential' and 'sign credential' endpoints.

#### Objectives:
- To simplify the interaction with the identity wallet by merging two endpoints into one.
- To create a standardized interface for credential issuance and signing.
- To encapsulate wallet-specific implementations and provide a consistent experience to the portal.

#### Architecture

<img width="670" alt="image" src="https://github.com/eclipse-tractusx/sig-release/assets/94133633/2b26423b-157d-494b-bb90-2c8e910b2cbe">

#### Acceptance Criteria:
1. **Wrapper Creation:**
   - Develop a wrapper that interfaces with both 'store credential' and 'sign credential' endpoints.
   - The wrapper should expose a single, standardized endpoint to the portal.

2. **Functionality:**
   - The wrapper must support all functionalities provided by the two separate endpoints.
   - Ensure that the wrapper can store and sign credentials as per the current implementation.

3. **Error Handling:**
   - Implement comprehensive error handling within the wrapper to manage any issues arising from the underlying endpoints.
   - Ensure that meaningful error messages are relayed back to the portal.

4. **Security:**
   - Ensure that the wrapper maintains the security standards required for handling credentials.
   - Implement necessary authentication and authorization checks within the wrapper.

5. **Testing:**
   - Write unit tests for the wrapper to ensure that both functionalities work as expected.
   - Conduct integration tests to verify that the wrapper interacts correctly with the identity wallet.

6. **Documentation:**
   - Document the API exposed by the wrapper, including request and response formats.
   - Update any existing documentation to reflect the change to a single endpoint.

#### Non-Functional Requirements:
- The wrapper should be designed to be scalable and maintainable.
- Performance should not be negatively impacted by the introduction of the wrapper.

#### Dependencies:
- Issuance Component code change (main component)
- MIW (impacted)
  After pre-analyzing with MIW no technical adaptations on MIW side are expected.

#### Risks:
- Potential security risks associated with merging two endpoints into one.
- The complexity of handling different operations in a single endpoint without introducing bugs.

#### Documentation:
- A detailed API specification for the new wrapper endpoint.
- Developer guide on how to integrate with the new wrapper.
- Update architectural diagrams to include the wrapper component.
- **Standard document** update needed CX-0149

**Comment by stephanbcbauer** [comment]
Was presented in the open planning ⇾ responsible committers are already defined

**Comment by stephanbcbauer** [comment]
Hello @jjeroch , @evegufy  

Since the feature is a 24.08 feature and the development phase is coming to an end, we need a status on the feature.

- [ ] Currently you are assigned (Responsible) → Is this correct? If not, please assign the correct contact person
- [ ] Please check whether the status (backlog, work in progress ...) is set correctly
- [ ] Please check whether there is an assignment to a committee or expert group (supported-by) to be found on the [board](https://github.com/orgs/eclipse-tractusx/projects/26/views/28)
- [ ] Please comment on the current status of the feature
- [ ] Are all SubTasks (issues from other repositories that deal with the feature) linked? → The easiest way is to mention the feature here in the issue (via the ID) so we can see which teams/repositories are involved.

If you need any clarification, please get in touch, thank you very much.
Stephan

**Comment by jjeroch** [comment]
**Updates**
- release updated to 24.12.
- implementation not yet started

**Comment by evegufy** [comment]
Committers:
@evegufy 
@Phil91 
@ntruchsess 
@oyo

**Comment by MaximilianHauer** [comment]
@Phil91  / @jjeroch  i assume we can close this issue ?
