### ISSUE TITLE
[Data Governance] KIT Release 24.08

### ISSUE THREAD

**Issue by dg-tsy** [eclipse-tractusx/sig-release#648]
As a Data Governance KIT Team,
We want to make sure that the following activities are taken care of for the 24.08 release

- Revise the KIT documentation and update the missing parts, if any
- Update the latest changes in the existing API specifications
- Update the Connector Management API to include other required URLs e.g. dsp URL and default URL for health services

So that the KIT remains up-to-date.

**Comment by danielmiehle** [comment]
Not included in the Release 24.05. - not PR provided.

**Comment by stephanbcbauer** [comment]
Hello @dg-tsy  

Since the feature is a 24.08 feature and the development phase is coming to an end, we need a status on the feature.

- [ ] Currently you are assigned (Responsible) → Is this correct? If not, please assign the correct contact person
- [ ] Please check whether the status (backlog, work in progress ...) is set correctly
- [ ] Please check whether there is an assignment to a committee or expert group (supported-by) to be found on the [board](https://github.com/orgs/eclipse-tractusx/projects/26/views/28)
- [ ] Please comment on the current status of the feature
- [ ] Are all SubTasks (issues from other repositories that deal with the feature) linked? → The easiest way is to mention the feature here in the issue (via the ID) so we can see which teams/repositories are involved.

If you need any clarification, please get in touch, thank you very much.
Stephan
