### ISSUE TITLE
Hardening and improve resilience of IRS

### ISSUE THREAD

**Issue by mkanal** [eclipse-tractusx/sig-release#650]
## Description
Hardening the irs to improve the resilience of the irs in relation to shared services. Reduce coupling of irs to shared services. Add versioning to be backward compatible. 

## Links 
- parent of https://github.com/eclipse-tractusx/item-relationship-service/issues/405
- parent of https://github.com/eclipse-tractusx/item-relationship-service/issues/470
- parent of https://github.com/eclipse-tractusx/item-relationship-service/issues/226
- parent of https://github.com/eclipse-tractusx/item-relationship-service/issues/392

## Impact
- 

## Additional information 

- [ ] I'm willing to contribute to this feature

**Comment by stephanbcbauer** [comment]
was presented in open planning -> contributors and committer are involved

**Comment by stephanbcbauer** [comment]
Hello @jzbmw, @mkanal 

Since the feature is a 24.08 feature and the development phase is coming to an end, we need a status on the feature.

- [ ] Currently you are assigned (Responsible) → Is this correct? If not, please assign the correct contact person
- [ ] Please check whether the status (backlog, work in progress ...) is set correctly
- [ ] Please check whether there is an assignment to a committee or expert group (supported-by) to be found on the [board](https://github.com/orgs/eclipse-tractusx/projects/26/views/28)
- [ ] Please comment on the current status of the feature
- [ ] Are all SubTasks (issues from other repositories that deal with the feature) linked? → The easiest way is to mention the feature here in the issue (via the ID) so we can see which teams/repositories are involved.

If you need any clarification, please get in touch, thank you very much.
Stephan

**Comment by stephanbcbauer** [comment]
Hello @jzbmw , @mkanal 
 
In a few weeks, we want to publish Tractus-X Release 24.08. For this, we need a clear status about the features (which will be included in the release and which will be cancelled or postponed to the next release).
 
Currently, the feature is still in status `Work in progress`. Please update the status by 09.07.24 eob.
 
If the feature is not ready for release 24.08, or it is possibly not planned at all, please set the status to `Not in release`. Please remember that in this case, any dependent components must be informed.
 
Thank you and best regards.

**Comment by mkanal** [comment]
Hello @stephanbcbauer 
#226 is currently in progress. 
In scope for 24.8

**Comment by mkanal** [comment]
@ds-jhartmann please close issue once https://github.com/eclipse-tractusx/sig-release/issues/226 is done

**Comment by ds-jhartmann** [comment]
https://github.com/eclipse-tractusx/item-relationship-service/issues/226 is done, closing this issue
