### ISSUE TITLE
EDC - Multi Wallet Support

### ISSUE THREAD

**Issue by lgblaumeiser** [eclipse-tractusx/sig-release#708]
## Description

Currently, the Tractus-X data space connector does only support the SAP DIM for validating credentials. With this feature, it should be possible to run the connector with different wallet implementation, like the [Managed Identity Wallet](https://github.com/eclipse-tractusx/managed-identity-wallet) or the [identity hub](https://github.com/eclipse-edc/IdentityHub), which support the Decentralised Claims Protocol natively. In addition, the implementation should not depend on any internal wallet reference, but should make use of the consumer reference of his wallet, basically provided by the consumer's DID.

## Impact

With this feature, first of all, we enable the selection of the wallet to be used within the data space. It enables multi-wallet scenarios, i.e., from connector side, with this feature everything is prepared to move from a central wallet to a decentralized wallet approach. In addition, there should be no constraint left from the connector to do the transition from a central wallet to decentralized wallet in a non-breaking fashion.

## Additional information 

- [ ] I'm willing to contribute to this feature

**Comment by jjeroch** [comment]
@lgblaumeiser following suggestions:

- reference to the standard would be useful. While adding the reference, please also add a short information IF a change of the standard is expected or not. Actually it sounds like it when reading the description. The standard is referring to the IATP for the presentation flow which is actually very generic and not linked to any provider; due to that I wouldn't expect a change.
- the named solutions "MIW" or "Identity Hub" are quite generic. MIW is nothing which can get claimed by Catena-X. We should specifically mention to which repo/product we are referring here. At the moment this is not clear, if you are not a Catena-X contribution member yes. MIW (Managed Identity Wallet) could be any wallet which is a managed solution.

Is there an active contribution commitment already existing?

**Comment by lgblaumeiser** [comment]
Hi @jjeroch:
Actually, the issue is an implementation only. Currently, the connector composition available in Tractus-X supports only the DIM because there were shortcuts done to make the DIM work. These shortcuts prevent that wallets that natively support the Decentralized Claims Protocol are usable with the EDC.

The current work on the MXD shows, that a different compilation of the connector is able to work with the managed identity identity wallet, so everything from a code perspective should already be available. The issue is only to abstract the handling in the connector in a way, that the shortcuts introduced due to time constraints for the 24/05 release are abstracted in a way, that existing alternative wallet implementations are supported as well besides the DIM.

I have added links to the wallet implementations to specify the meaning of the names more precisely.

**Comment by lgblaumeiser** [comment]
Already part of Tractus-X release 0.8.0
