### ISSUE TITLE
EDC - Multiple EDC management and Catalog Federation

### ISSUE THREAD

**Issue by DanielaWuensch** [eclipse-tractusx/sig-release#736]
**Scenario:** A data provider operates multiple EDC connectors and data catalogs

**Problem:** If a data consumer is unaware of which EDC holds the desired offer, he needs to iterate over all catalogs, that's quite inefficient.

**Proposed solution:** Concept to manage multiple EDCs to federate their catalogs and expose them in a unified manner is done here https://github.com/eclipse-edc/Connector/blob/main/docs/developer/management-domains/management-domains.md and need to be implemented

**Impacted components**

- Upstream EDC
- Tractus-X EDC
- DSP for get catalogue?
- CX-0018?

**Comment by jimmarino** [comment]
Management domains will help enable this. However, the reason there are multiple URLs is because it was decided some time ago to have a central service that resolves connector URLs (emphasis on plural) for a participant. Before decentralized identities, this made sense because `DIDs` were not used. However, that is not the case anymore. 

It's also worth noting that the current approach to resolving connector URLs is not aligned with the `DSP` and `DCAT` specifications, which embed endpoint information in `DID` documents and `DCAT catalogs.` In order to come up with a complete solution, we need the following:

1. Management domains
2. Federated Catalog integration with TX-EDC
3. A change to the core CX service

**Comment by stephanbcbauer** [comment]
Presented in the DRAFT Feature Freeze -> Committer is available
Impact on how the catalogue is provided

**Comment by lgblaumeiser** [comment]
Hi @paullatzelsperger @rafaelmag110 , last time we talked about the issue, there was a reference to a documentation PR which needed to be merged. Is this done? Could you then please close this issue? Thanks!

**Comment by rafaelmag110** [comment]
Hi @lgblaumeiser, that documentation PR is not related to this issue in specific. This can be closed.
