### ISSUE TITLE
Knowledge Agent Release 23.12 Security Acceptance Criteria

### ISSUE THREAD

**Issue by kelaja** [eclipse-tractusx/sig-release#91]
# Release Security 23.12

Source in Catena-X Confluence and Expert Contacts [here](https://confluence.catena-x.net/x/DOZkBQ)(Source only accessible for Catena-X Consortia members in current transition phase).

- [x] **Threat Modelling Analysis results**
  Analysis completed (operations excluded):
  
    - List of risks generated or updated, rated & actions defined
    - Risks accepted or mitigation actions implemented and tested
    - no high threats acceptable

  _Artifact Repository:_
  
    - risk register (decentral on Catena-X confluence)

  _Prime Contacts:_
  
    - Security Team: SEC0

- [x] **Static Application Security Testing (SAST)**
  - code must be scanned weekly with Veracode tool
  - medium risks require mitigation statement
  - high and above not accepted

  _Best Practise:_
  
    - Confirm relevant repository as early as possible to SEC team to enable regular, automated scans. Evidence required for Gate approval.

  _Artifact Repository:_
  
    - Veracode UI
    - (+ GitHub Action)

  _Prime Contacts:_
  
    - Security Team: SEC1

- [x] **Dynamic Application Security Testing (DAST)**
  incl API testing (if applicable)
  - all findings assessed
  - high & very high findings mitigated
  - evidence by re-scan

  _Best Practise:_
  
    - Confirm relevant repository as early as possible to SEC team to enable regular, automated scans. Evidence required for Gate approval.

  _Artifact Repository:_
  
    - INVICTI tool

  _Prime Contacts:_
  
    - Security Team: SEC3 SEC4

- [x] **Secret scanning**
  Scan executed centrally by SEC team and ZERO valid findings
  
  _Artifact Repository:_
  
    - Veracode or alternative tool
    - GitHub Secret Scanning
    - GitGuardian

  _Best Practise:_
  
    - Confirm relevant repository as early as possible to SEC team to enable regular, automated scans. Evidence required for Gate approval.

   _Prime Contact:_
  
     - Security Team: SEC1

- [x] **Software Composition Analysis (SCA)**
  Dependencies must be scanned with Veracode tool with regards to vulnerability
    - high and above not accepted
    - FOSS whitelist policy has to be passed

  _Best Practise:_
  
    - Confirm relevant repository as early as possible to SEC team to enable regular, automated scans. Evidence required for Gate approval.

  _Artifact Repository:_
  
    - Veracode UI
    - (& GitHub Action)

  _Prime Contacts:_
  
    - Security Team: SEC1

- [x] **Container Scan conducted**
  All containers in GitHub Packages must be scanned
  
    - High / Critical findings not accepted

  _Best Practise:_
  
    - Confirm relevant repository as early as possible to SEC team to enable regular, automated scans. Evidence required for Gate approval.

  _Artifact Repository:_
  
    - Trivy
    - via nightly GitHub Action

  _Prime Contacts:_
  
    - Security Team: SEC2

- [x] **Infrastructure as Code**
  IaC code must be scanned. 
    - Error findings not accepted

   _Best Practise:_
  
    - Confirm relevant repository as early as possible to SEC team to enable regular, automated scans. Evidence required for Gate approval.

  _Artifact Repository:_
  
    - KICS or alternative tool
    - via nightly GitHub Action

  _Prime Contacts:_
  
    - Security Team: SEC2

**Comment by klaudiaZF** [comment]
Hi All,

knowledge-agents-edc/agentplane-hashicorp

<img width="836" alt="knowledge-agents-edc_agentplane-hashicorp" src="https://github.com/eclipse-tractusx/sig-release/assets/148344761/b0217338-7af6-44d9-a4eb-b0c63e0c0fa6">


**SCA Did not pass due to high finding**

knowledge-agents-edc/agentplane-azure-vault

<img width="834" alt="knowledge-agents-edc_agentplane-azure-vault" src="https://github.com/eclipse-tractusx/sig-release/assets/148344761/26e8624c-3e37-46ff-9d4f-8f7b5e95201b">


**SCA Did not pass due to high findings**

knowledge-agents/remoting-agent

<img width="833" alt="knowledge-agents_remoting-agent" src="https://github.com/eclipse-tractusx/sig-release/assets/148344761/ad4f6175-e4d9-467d-a10d-98a3721b2f2f">


**SCA Did not pass due to high findings**

knowledge-agents/conforming-agent

<img width="832" alt="knowledge-agents_conforming-agent" src="https://github.com/eclipse-tractusx/sig-release/assets/148344761/cb8d6838-dd9e-47c6-b2b1-08a61018df92">


**SCA Passed**

knowledge-agents/provisioning-agent

<img width="837" alt="knowledge-agents_provisioning-agent" src="https://github.com/eclipse-tractusx/sig-release/assets/148344761/2ae43996-df4c-4224-a65b-85b4497d5cc7">


**SCA Did not pass due to high findings**

**Comment by klaudiaZF** [comment]
Hi All,
After today's scanning knowledge-agents-edc/agentplane-hashicorp changed to passed.

<img width="838" alt="knowledge-agents-edc_agentplane-hashicorp_new" src="https://github.com/eclipse-tractusx/sig-release/assets/148344761/cb646d14-1ab4-4226-bbb8-6f36a038e79b">


**SCA Passed for knowledge-agents-edc/agentplane-hashicorp**

**Comment by PiotrStys** [comment]
Hello, 

No high vulnerabilities reported back by OWASP ZAP.
Others have been assessed and approved.


![Image](https://github.com/eclipse-tractusx/sig-release/assets/140413055/519d3818-a42d-4d2d-98bf-f0d08a85da28)


**DAST Passed**

Thanks,
Piotr

**Comment by drcgjung** [comment]
Hi all - all modules should now be green (SAST + SCA, Container modulo base image [temurin/jammy] vulnerabilities)

![image](https://github.com/eclipse-tractusx/sig-release/assets/3089344/bfc6306e-ad3e-4e9c-9f1b-5e654e523c99)

**Comment by DnlZF** [comment]
Hi,
there are no open GitGuardian findings:
![image](https://github.com/eclipse-tractusx/sig-release/assets/99189503/9dd45106-24a7-4105-8710-654058b31a18)
-> **Secret scanning approved**

Best regards
Daniel

**Comment by klaudiaZF** [comment]
Hi All and @drcgjung 

Everything is on green now

**SCA Passed**


<img width="834" alt="knowledge-agents-conforming-agent" src="https://github.com/eclipse-tractusx/sig-release/assets/148344761/3628fef1-7753-456a-b427-f2ba598045fd">
<img width="835" alt="knowledge-agents-edc-agentplane-azure-vault" src="https://github.com/eclipse-tractusx/sig-release/assets/148344761/29c152e9-f15e-42b7-86cd-3d4335ace3a4">
<img width="836" alt="knowledge-agents-edc-agentplane-hashicorp" src="https://github.com/eclipse-tractusx/sig-release/assets/148344761/6e434fcc-b9f5-4646-babd-236fbdfbca5b">
<img width="835" alt="knowledge-agents-provisioning-agent" src="https://github.com/eclipse-tractusx/sig-release/assets/148344761/02a3884e-8d49-4dc6-b134-4e71653a3dad">
<img width="833" alt="knowledge-agents-remoting-agent" src="https://github.com/eclipse-tractusx/sig-release/assets/148344761/221edcd6-564f-42e9-ac5d-9b0a02e99f2e">

**Comment by kelaja** [comment]
- @drcgjung kindly verfify Container Check for approval

**Comment by drcgjung** [comment]
Here are the trivy findings for knowledge-agents-edc. Shows that only high/medium finding of the base images are left (see the DevOps discussion, OSS requirements weigh higher)

![image](https://github.com/eclipse-tractusx/sig-release/assets/3089344/b2d0220c-5311-4d79-b782-8a1c238af545)

![image](https://github.com/eclipse-tractusx/sig-release/assets/3089344/b604d6ee-6abd-4d6d-b6ae-ac870f3edcd8)

**Comment by drcgjung** [comment]
Here are the trivy findings for knowledge-agents. Since the release PR is pending on an IP check (https://github.com/eclipse-tractusx/knowledge-agents/pull/66), we show both the already published 1.10.15-SNAPSHOT (main) as well as a locally-built preview results on 1.10.15. Shows that only high/medium finding of the base images are left (see the DevOps discussion, OSS requirements weigh higher than security). Note that we had to derive from base images in the case of strong runtime dependencies on RDF4J SDK (remoting-agent) and Ontop VKP (provisioning-agent)

![image](https://github.com/eclipse-tractusx/sig-release/assets/3089344/44697755-c139-432f-bf6e-3952e75d4e75)
![image](https://github.com/eclipse-tractusx/sig-release/assets/3089344/5b14a9bd-90f9-46fe-ab2d-33a6526bbba6)

![image](https://github.com/eclipse-tractusx/sig-release/assets/3089344/26ac3f09-d5f5-4e7e-a76f-23eca0c4f637)
![image](https://github.com/eclipse-tractusx/sig-release/assets/3089344/67042dae-3afc-474e-af44-a0da94e74128)

![image](https://github.com/eclipse-tractusx/sig-release/assets/3089344/7124ff9a-f56d-489e-9054-cb9aebb2ebe2)
![image](https://github.com/eclipse-tractusx/sig-release/assets/3089344/254b8989-bba2-44c8-93e2-278f01435f72)

**Comment by klaudiaZF** [comment]
Hi All,

**SAST passed**

<img width="833" alt="knowledge-agents-edc-agentplane-azure-vault" src="https://github.com/eclipse-tractusx/sig-release/assets/148344761/8cbdefda-e169-4d85-9e49-0bec80297128">
<img width="831" alt="knowledge-agents-edc-agentplane-hashicorp" src="https://github.com/eclipse-tractusx/sig-release/assets/148344761/81e0cc79-772d-4e37-a19b-bebc1a9cdede">
<img width="833" alt="knowledge-agents-provisioning-agent" src="https://github.com/eclipse-tractusx/sig-release/assets/148344761/cd2b02bd-3aa9-423a-a8eb-3cfe4ecb8586">
<img width="831" alt="knowledge-agents-conforming-agent" src="https://github.com/eclipse-tractusx/sig-release/assets/148344761/0aa558e1-4552-4d51-aae9-d068b8ab976e">
<img width="832" alt="knowledge-agents-remoting-agent" src="https://github.com/eclipse-tractusx/sig-release/assets/148344761/a32faa44-df4b-4ea2-9adf-6389a1c5544a">

Just please keep in mind that we have few open medium findings:
<img width="946" alt="knowledge-agents-edc-agentplane-azure-vault1" src="https://github.com/eclipse-tractusx/sig-release/assets/148344761/ed485040-5ca7-4681-95a1-be8f30a10e8f">

**Comment by scherersebastian** [comment]
> Here are the trivy findings for knowledge-agents. Since the release PR is pending on an IP check ([eclipse-tractusx/knowledge-agents#66](https://github.com/eclipse-tractusx/knowledge-agents/pull/66)), we show a locally-built preview results on 1.10.15. Shows that only high findings of the base images are left (see the DevOps discussion, OSS requirements weigh higher than security). Note that we had to derive from base images in the case of strong runtime dependencies on RDF4J SDK (remoting-agent) and Ontop VKP (provisioning-agent)
> 
> ![image](https://private-user-images.githubusercontent.com/3089344/285399419-5b14a9bd-90f9-46fe-ab2d-33a6526bbba6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyNjY1MDEsIm5iZiI6MTcwMTI2NjIwMSwicGF0aCI6Ii8zMDg5MzQ0LzI4NTM5OTQxOS01YjE0YTliZC05MGY5LTQ2ZmUtYWIyZC0zM2E2NTI2YmJiYTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTEyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzExMjlUMTM1NjQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDY3MDYzZjlmOGJhNDUxNmMxOGYzMmQwMWZmMGY4YzIxZWFkZWNhNzBmNmIzNTQ0YzRmODQxMmNhNTFlN2JkZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ZKDZMqfdEa1yFjKpHKsqFwG7ms_d00fGnFUcHUHVK8Y)
> 
> ![image](https://private-user-images.githubusercontent.com/3089344/285407794-c03393a6-d7ce-4f38-bc0d-5791e1a5c729.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyNjY1MDEsIm5iZiI6MTcwMTI2NjIwMSwicGF0aCI6Ii8zMDg5MzQ0LzI4NTQwNzc5NC1jMDMzOTNhNi1kN2NlLTRmMzgtYmMwZC01NzkxZTFhNWM3MjkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTEyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzExMjlUMTM1NjQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDY3OTkzOWUzYTJhNTljOGZkOWEwNTU2MDJjOTgwYTMwNTA1YjkxNjA3MGQ1YjAzZWJiMDE4YzRkN2RjMDdjOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.x8A4OGj7TF_UmaidfH8-SWgB94KiymKATh8vQSKWH64)
> 
> ![image](https://private-user-images.githubusercontent.com/3089344/285407243-d45c7d50-17d0-4db7-9f76-e6c50e4863ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyNjY1MDEsIm5iZiI6MTcwMTI2NjIwMSwicGF0aCI6Ii8zMDg5MzQ0LzI4NTQwNzI0My1kNDVjN2Q1MC0xN2QwLTRkYjctOWY3Ni1lNmM1MGU0ODYzYWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTEyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzExMjlUMTM1NjQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTIyZWM0YmNlMjM0Yzg4ZDE1YjBmYjI2ZjJiMmRkM2QwNTg3YjEwNmQwMGYxNTdhODcwNWIwMjk1YmJhZWJjOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.29sjcR5bugHNRX1sdNbDjMQ95B0mzZJX10fRxDZP_uo)

as @drcgjung stated.
kics passed

**Comment by drcgjung** [comment]
@kelaja @scherersebastian Container Scan for knowledge-agents (IP check through, release done) should now also be green. Aaaaah thats all a moving target, another medium for spring-boot ... feeling like sisiphos. 

A29078924@T000c60ad4 Applications % trivy image tractusx/remoting-agent:1.10.15
2023-11-29T15:36:42.005+0100	INFO	Need to update DB
2023-11-29T15:36:42.005+0100	INFO	DB Repository: ghcr.io/aquasecurity/trivy-db
2023-11-29T15:36:42.005+0100	INFO	Downloading DB...
41.10 MiB / 41.10 MiB [------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------] 100.00% 5.97 MiB p/s 7.1s
2023-11-29T15:36:50.546+0100	INFO	Vulnerability scanning is enabled
2023-11-29T15:36:50.546+0100	INFO	Secret scanning is enabled
2023-11-29T15:36:50.546+0100	INFO	If your scanning is slow, please try '--scanners vuln' to disable secret scanning
2023-11-29T15:36:50.546+0100	INFO	Please see also https://aquasecurity.github.io/trivy/v0.45/docs/scanner/secret/#recommendation for faster secret detection
2023-11-29T15:36:50.578+0100	INFO	Detected OS: ubuntu
2023-11-29T15:36:50.578+0100	INFO	Detecting Ubuntu vulnerabilities...
2023-11-29T15:36:50.579+0100	INFO	Number of language-specific files: 1
2023-11-29T15:36:50.579+0100	INFO	Detecting jar vulnerabilities...

tractusx/remoting-agent:1.10.15 (ubuntu 22.04)

Total: 35 (UNKNOWN: 0, LOW: 24, MEDIUM: 11, HIGH: 0, CRITICAL: 0)

A29078924@T000c60ad4 Applications % trivy image tractusx/provisioning-agent:1.10.15
2023-11-29T15:38:39.564+0100	INFO	Vulnerability scanning is enabled
2023-11-29T15:38:39.564+0100	INFO	Secret scanning is enabled
2023-11-29T15:38:39.564+0100	INFO	If your scanning is slow, please try '--scanners vuln' to disable secret scanning
2023-11-29T15:38:39.564+0100	INFO	Please see also https://aquasecurity.github.io/trivy/v0.45/docs/scanner/secret/#recommendation for faster secret detection
2023-11-29T15:38:43.002+0100	INFO	JAR files found
2023-11-29T15:38:43.010+0100	INFO	Java DB Repository: ghcr.io/aquasecurity/trivy-java-db:1
2023-11-29T15:38:43.010+0100	INFO	Downloading the Java DB...
483.92 MiB / 483.92 MiB [---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------] 100.00% 4.92 MiB p/s 1m39s
2023-11-29T15:40:23.599+0100	INFO	The Java DB is cached for 3 days. If you want to update the database more frequently, the '--reset' flag clears the DB cache.
2023-11-29T15:40:23.602+0100	INFO	Analyzing JAR files takes a while...
2023-11-29T15:40:23.711+0100	INFO	Detected OS: ubuntu
2023-11-29T15:40:23.711+0100	INFO	Detecting Ubuntu vulnerabilities...
2023-11-29T15:40:23.712+0100	INFO	Number of language-specific files: 1
2023-11-29T15:40:23.712+0100	INFO	Detecting jar vulnerabilities...

tractusx/provisioning-agent:1.10.15 (ubuntu 22.04)

Total: 32 (UNKNOWN: 0, LOW: 22, MEDIUM: 10, HIGH: 0, CRITICAL: 0)

And that one is using the official TX base image

A29078924@T000c60ad4 Applications % trivy image tractusx/conforming-agent:1.10.15
2023-11-29T15:40:46.772+0100	INFO	Vulnerability scanning is enabled
2023-11-29T15:40:46.772+0100	INFO	Secret scanning is enabled
2023-11-29T15:40:46.772+0100	INFO	If your scanning is slow, please try '--scanners vuln' to disable secret scanning
2023-11-29T15:40:46.772+0100	INFO	Please see also https://aquasecurity.github.io/trivy/v0.45/docs/scanner/secret/#recommendation for faster secret detection
2023-11-29T15:40:48.321+0100	INFO	JAR files found
2023-11-29T15:40:48.322+0100	INFO	Analyzing JAR files takes a while...
2023-11-29T15:40:48.364+0100	INFO	Detected OS: alpine
2023-11-29T15:40:48.364+0100	INFO	Detecting Alpine vulnerabilities...
2023-11-29T15:40:48.366+0100	INFO	Number of language-specific files: 1
2023-11-29T15:40:48.366+0100	INFO	Detecting jar vulnerabilities...

tractusx/conforming-agent:1.10.15 (alpine 3.18.4)

Total: 4 (UNKNOWN: 0, LOW: 0, MEDIUM: 2, HIGH: 2, CRITICAL: 0)

![image](https://github.com/eclipse-tractusx/sig-release/assets/3089344/3aa0af74-a0d6-4f2b-b7b6-9258bd1e9bb7)


I have the idea of using the non-base images for 24.03 no more as runtime, but just as "build container" and then repackage the stuff into the official base image. Because its all JRE-based this should not be too difficult.

**Comment by scherersebastian** [comment]
If you can't remove the libraries and install the fixed ones, and there is no way around - then please commit yourself to a hot fix as soon as you can fix it. 
@drcgjung I trust your assessment, you as a developer know your app best, if you say there is no way - you are passed, with the commitment of a fix.
We should not discuss open Findings this openly!

**Comment by drcgjung** [comment]
here is the commitment https://github.com/eclipse-tractusx/knowledge-agents/issues/72

**Comment by scherersebastian** [comment]
> here is the commitment https://github.com/eclipse-tractusx/knowledge-agents/issues/72

Passed :)
