### ISSUE TITLE
Knowledge Agent Release 23.12 Test Results Acceptance Criteria

### ISSUE THREAD

**Issue by kelaja** [eclipse-tractusx/sig-release#92]
# Release Test Results 23.12

Source in Catena-X Confluence and Expert Contacts [here](https://confluence.catena-x.net/x/DOZkBQ)(Source only accessible for Catena-X Consortia members in current transition phase).

- [x] **E2E System Integrations Tests**

  -  To pass the Consortia Gate 4, evidence has to be made available that all test criteria up to and including TRL 4 & TRL 6 have been achieved.
  - Expected evidence = outputs of TRL 4 and TRL 6.
  - Test Management has mapped and described all mandatory tests for Consortia Quality Gates [HERE](https://confluence.catena-x.net/x/WQpHAw)(Source only accessible for Catena-X Consortia members in current transition phase).
  - Please focus on the columns "Derived Criteria" and "Outputs"  
  - Document your test results in Catena-X JIRA XRAY
  - Use the fields “DoD” and “Status” (story & solution level) to approve requirements.
  - Interim test results are required after Tests of each Sprint, this is pre-requisite to participate in E2E test phase

  _Contact:_
    - TEST MANAGEMENT

- [x] **Approval of User Journey**

  - CX Business Owner confirms: All acceptance criteria met (as defined in PI documentation)
  Relevant evidence is available

  _Artifact Repository_
    - [Jira Solution Level](https://jira.catena-x.net/projects/CXSOLUTION/summary)(Source only accessible for Catena-X Consortia members in current transition phase)
  
  _Best Practise_
    - PO to obtain BO approval prior to Gate review.
    - BO therefore to evaluate progress by participation at iteration demos.
    - BOs provide E2E test cases.
    - BOs welcome to act as tester.
    - BOs expected to participate in System Demo.

  _Contacts:_
    - FOSS Product Owners &
    - CX Business Owners

**Comment by bosserf** [comment]
ich gebe in der Rolle des BO hiermit mein Approval -> selber kann ich den Haken nicht setzen: Wer macht's?

**Comment by kelaja** [comment]
@bosserf ich übernehme 👍🏼

**Comment by drcgjung** [comment]
As discussed in yesterday's meeting and because not all test participants have Jira Access, we would document the integration and E2E tests using the following markdown table. The particpants would fill the "results" column and send their bit either as a comment to this thread or via email to @BerndRothbrust.

# Knowledge Agents Integration Test Suite 23.12

##  Knowledge Agent Integration Test Plan "Consumer" 23.12 (ADAC)

|  Step  |  Content  |  Expected |  Result | Status  |
|---|---|---|---|---|
| Deploy Agent-Enabled Connector  |  Use OSS Helm-Chart. Use INT SSI/MIW Settings. Add OEM BPNL and Connector for synchronisation. |  Two Pods/Services (Control Plane and Agent Data Plane) healthy. |   | <ul><li>[ ] Ok</li></ul>  |
| Perform Remote Catalogue Request   | Use OEM Connector as ProviderUrl  |  The asset GraphAsset?oem=BehaviourTwinReliability should have at least one offer  |   |  <ul><li>[ ] Ok</li></ul>  |
| Check Federated Catalogue  | In the agent plane log, there should be frequent synchronisation entries. | Entries associated with the OEM Connector should show "xx tuples inserted" where xx is >0   |   |  <ul><li>[ ] Ok</li></ul>  |

##  Knowledge Agent Integration Test Plan "OEM" 23.12 (BMW)

|  Step  |  Content  |  Expected |  Result | Status  |
|---|---|---|---|---|
| Deploy Agent-Enabled Connector  |  Use Self-Compiled Images From OSS Artifacts and Own Deployment Scripts. Add SUPPLIER BPNL and Connector for synchronisation. |  Two Pods/Services (Control Plane and Agent Data Plane) healthy. |   | <ul><li>[ ] Ok</li></ul>  |
| Perform Remote Catalogue Request   | Use SUPPLIER Connector as ProviderUrl  |  The asset GraphAsset?supplier=BehaviourTwinRUL should have at least one offer  |   |  <ul><li>[ ] Ok</li></ul>  |
| Check Federated Catalogue  | In the agent plane log, there should be frequent synchronisation entries. | Entries associated with the SUPPLIER Connector should show "xx tuples inserted" where xx is >0   |   |  <ul><li>[ ] Ok</li></ul>  |
| Deploy Provisioning Agent  |  Use OSS Images and Own Deployment Scripts. Add a reliability binding to the existing telematics database. |  One Pod/Service (Provisioning Agent) healthy. |   | <ul><li>[ ] Ok</li></ul>  |
| Access Provisioning Agent  |  Use SPARQL query to access reliabiility graph. |  A non-emtpy result set should be returned. |   | <ul><li>[ ] Ok</li></ul>  |
| Register Graph Asset  |  Publish Graph Asset along KA specification with the provisioning agent service in the dataaddress. |  Registration successful. |   | <ul><li>[ ] Ok</li></ul>  |
| Register Graph Policy  |  Publish Graph Policy along KA specification with the CONSUMER BPNL allowed. |  Registration successful. |   | <ul><li>[ ] Ok</li></ul>  |
| Register Graph Contract  |  Publish Graph Contract along KA specification with the Graph Asset in the selector and the Graph policy for access and contract.  |  Registration successful. |   | <ul><li>[ ] Ok</li></ul>  |

##  Knowledge Agent Integration Test Plan "SUPPLIER" 23.12 (ZF)

|  Step  |  Content  |  Expected |  Result | Status  |
|---|---|---|---|---|
| Deploy Agent-Enabled Connector  |  Use OSS Helm Chart |  Two Pods/Services (Control Plane and Agent Data Plane) healthy. |   | <ul><li>[ ] Ok</li></ul>  |
| Deploy Remoting Agent  |  Use OSS Images and Own Deployment Scripts. Add a behaviour/rul binding to the existing prognosis service with the remoting agent service as a callback. |  One Pod/Service (Remoting Agent) healthy. |   | <ul><li>[ ] Ok</li></ul>  |
| Access Remoting Agent  |  Use SPARQL query to access behaviour/rul graph. |  A non-emtpy result set should be returned. |   | <ul><li>[ ] Ok</li></ul>  |
| Register Graph Asset  |  Publish Graph Asset along KA specification with the remoting agent service in the dataaddress. |  Registration successful. |   | <ul><li>[ ] Ok</li></ul>  |
| Register Graph Policy  |  Publish Graph Policy along KA specification with the OEM BPNL allowed. |  Registration successful. |   | <ul><li>[ ] Ok</li></ul>  |
| Register Graph Contract  |  Publish Graph Contract along KA specification with the Graph Asset in the selector and the Graph policy for access and contract.  |  Registration successful. |   | <ul><li>[ ] Ok</li></ul>  |

# Knowledge Agents E2E Test Suite 23.12

## Knowledge Agents E2E Test Plan "CONSUMER" 23.12 (ADAC)

|  Step  |  Content  |  Expected |  Result | Status  |
|---|---|---|---|---|
| Register RUL skill  |  Post Parameterized SPARQL to Agent/Skill Endpoint under SkillAsset?consumer=RemainingUsefulLife |  Registration successful. |   | <ul><li>[ ] Ok</li></ul>  |
| Invoke RUL skill  |  Post VAN(s) to Agent Endpoint referring SkillAsset?consumer=RemainingUsefulLife  |  A non-empty result set should be returned. |   | <ul><li>[ ] Ok</li></ul>  |

**Comment by kelaja** [comment]
@drcgjung @BerndRothbrust kindly update, ThX

**Comment by BerndRothbrust** [comment]
OK from TM @kelaja your Task now

**Comment by RohitKumar-ZF** [comment]
| Step | Content | Expected | Result | Status |
|---|---|---|---|---|
| Deploy Agent-Enabled Connector | Use OSS Helm Chart | Two Pods/Services (Control Plane and Agent Data Plane) healthy. | control and agent plane pods and running| <ul><li>[x] Ok</li></ul> |
| Deploy Remoting Agent | Use OSS Images and Own Deployment Scripts. Add a behaviour/rul binding to the existing prognosis service with the remoting agent service as a callback. | One Pod/Service (Remoting Agent) healthy. | Remoting Agent pod is running| <ul><li>[x] Ok</li></ul> |
| Access Remoting Agent | Use SPARQL query to access behaviour/rul graph. | A non-emtpy result set should be returned. | Non-emtpy result returned.| <ul><li>[x] Ok</li></ul> |
| Register Graph Asset | Publish Graph Asset along KA specification with the remoting agent service in the dataaddress. | Registration successful. |Registration done | <ul><li>[x] Ok</li></ul> |
| Register Graph Policy | Publish Graph Policy along KA specification with the OEM BPNL allowed. | Registration successful. |Registration done | <ul><li>[x] Ok</li></ul> |
| Register Graph Contract | Publish Graph Contract along KA specification with the Graph Asset in the selector and the Graph policy for access and contract. | Registration successful. |Done | <ul><li>[x] Ok</li></ul> |

**Comment by dreni** [comment]
## Knowledge Agents E2E Test Plan "CONSUMER" 23.12 (ADAC)
 
|  Step  |  Content  |  Expected |  Result | Status  |
|---|---|---|---|---|
| Register RUL skill  |  Post Parameterized SPARQL to Agent/Skill Endpoint under SkillAsset?consumer=RemainingUsefulLifeE2E |  Registration successful. |   | <ul><li>[x] Ok</li></ul>  |
| Invoke RUL skill  |  Post VAN(s) to Agent Endpoint referring SkillAsset?consumer=RemainingUsefulLifeE2E  |  A non-empty result set should be returned. |   | <ul><li>[x] Ok</li></ul>  |

NOTE: E2E Executed between ADAC, Knowledge-Agent Dev Environment as OEM and ZF.
